### ISSUE TITLE
Node 8.0 support (was: Yarn install - Pre-built binaries not found 404)

### ISSUE THREAD

**Issue by luisfcofv** [realm/realm-js#1052]
I'm getting the following error while installing realm with yarn install or npm install.
```
node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/realm-v1.3.1-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@1.3.1 and node@8.0.0 (node-v57 ABI) (falling back to source compile with node-gyp)
```

Yarn version: v0.24.6

**Comment by kristiandupont** [comment]
We don't support Node 8.0 just yet.

**Comment by jbreuer95** [comment]
+1

**Comment by zphhhhh** [comment]
Is there any plan to support Node 8.0 ? And when?

**Comment by Jkaveri** [comment]
Are there anyway to work around?

**Comment by fealebenpae** [comment]
Realm should compile from source on Node version we don't ship prebuilt binaries for. Make sure you have a working compiler and the [node-gyp dependencies](https://github.com/nodejs/node-gyp#installation) installed so that npm can compile Realm when installing it.

We'll include Node.js 8.x binaries in our next release.

**Comment by ABYARTH** [comment]
Downgrading node version to 7.x.x worked for me.
