### ISSUE TITLE
Realm.List inherited functions seem missing in jest test

### ISSUE THREAD

**Issue by peteroid** [realm/realm-js#1096]
### Summary
When I was testing my model under Realm using Jest, it seems some functions were missing. For instance, `map()` and `keys()` would be missing and the test will throw the error saying `TypeError: xxx.map is not a function`. However, this error only happens in the jest but not in the normal execution.

After some trials, I found that replacing the map function from `xxx.map(fn)` to `Realm.List.prototype.map.call(xxx, fn)` could be working in both the jest test and normal execution.

### Expected results
`map` function should be defined in the List object

### Actual results
Jest threw errors like `TypeError: xxx.map is not a function`

### Version
* realm: 1.3.1
* node: 7.10.0
* jest: 20.0.4

**Comment by John251314** [comment]
I met the same problem. what is the solution, in addition to the above method. Thanks.

**Comment by benweidig** [comment]
We ran into this exact issue today, but we needed some(...) which isn't 
callable like that.

**Comment by kneth** [comment]
See also https://github.com/facebook/jest/issues/4603

**Comment by kneth** [comment]
@kraenhansen You have a hypothesis why it isn't working, right?

**Comment by kraenhansen** [comment]
> @kraenhansen You have a hypothesis why it isn't working, right?

I believed we have a similar issue with `for(let ... of ...) loop` on React Native. Originating from the way Realm JS is looping over the methods to export here: https://github.com/realm/realm-js/blob/master/lib/collection-methods.js#L49. I have a suspicion that some environments call the callback of `forEach` asynchronously.

But ... reading over the Jest issues, that you @kneth linked to, this does indeed seem like a known Jest bug. Perhaps a workaround could be found, but it seems more valuable to get the root cause fixed.

**Comment by takameyer** [comment]
@peteroid  We took some time to try and reproduce this issue and failed to reproduce it.  Can you try updating Jest and Realm, to see if the issue is resolved?

**Comment by takameyer** [comment]
The issues has been closed, as we are not able to reproduce it and no one in the community has reported that it is still an issue.  If someone is seeing this issue, feel free to yell and we will reopen the issue.
