### ISSUE TITLE
openAsync fires twice with an unexpected error for newly created realms

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#1140]
```js

let Realm = require('realm')

let admin = Realm.Sync.User.adminUser('ewoJImlkZW50aXR5IjogIl9fYXV0aCIsCgkiYWNjZXNzIjogWyJ1cGxvYWQiLCAiZG93bmxvYWQiLCAibWFuYWdlIl0KfQo=:WYLWgyTzDVn2BS/5vilJ7sbCuHyJBbslIKFW7jpknc0iL6l/vRqtp2H+RIV9/bmy4vbQDEdUksFKUpXprvKDZICam/930LSdgMPgIMEszz7r8iho1SBjfjCaniZ6DyAD9HxKLHhiDNe6W5LvViY1bAsHuLdLRYYlQxcrgG7SRhYNEXjrKJPzY46WWCbNh7x45UbPycZVRpfHOzUUuGLYGOnRbL0tokJm64+CYk7+C6BlGR32x4BL4v5unbBGj7+CVWTennY4ZhHQo9k/EyPuWZUwTjU2k505ziGp0FtFgiqK+XRFNodGdMqu7m8oZDEVY33/v+9rh0B2E/OI4yDCRg==')
let realm = new Realm({
	sync: {
		user: admin,
		url: 'realm://localhost:9080/test'
	}
})
realm.close()

Realm.openAsync({
	sync: {
		user: admin,
		url: 'realm://localhost:9080/test'
	}
}, (error, realm) => {
	console.log(error)
	console.log(realm)
})
```

This outputs
```
{ message: 'Operation canceled', errorCode: 89 }
undefined

null
Realm {}
```
indicating that the callback fires twice. The `Operation canceled` error is coming internally from Realm and is very misleading.

**Comment by alazier** [comment]
Until we fix this we need to add a mandantory delay of hundreds of ms to every test. This is not something which we can do in the long term.

**Comment by nirinchev** [comment]
`openAsyn` will throw `Operation canceled` if the realm doesn't exist on the server. Is this the case? The reason the callback gets invoked twice is this line:
https://github.com/realm/realm-js/blob/479e8eebaad16c2b90b66ae4648b6264da6c7f55/lib/extensions.js#L66

Instead of returning after the callback is invoked, the Realm is opened synchronously, this call succeeds and the callback is invoked with the newly opened Realm. While it's definitely a bug that needs to be fixed, you should make sure that in tests `openAsync` is not called for realms that don't exist on the server, otherwise when the bug is fixed, those tests will simply fail.
