### ISSUE TITLE
reset db

### ISSUE THREAD

**Issue by bleonard** [realm/realm-js#13]
For tests, we need to clear/truncate all the tables.
What's the best what to do that?
I'm currently iterating through each and `realm.objects(name).delete(results);`

Is there one method to start over the whole db?

**Comment by brunovalenga** [comment]
Hello, did not work for me :/

try {
  realm.write(() => {
    realm.deleteAll()
  })
} catch (err) {
  if (err) Promise.reject(new Error(`Error. Log: ${err}`))
}

I received this message:
Acecessing object of type Message which has been invalidated or deleted.

Obs; 'Message' is my schema.

**Comment by Selman555** [comment]
I'm @brunovalenga. I'm trying to fix this for me as well.
You most likely have some realm object references in your store (or something similar) that are still being called after you nuked realm.
Best thing to do would refresh your state to the initial state so that all references are collected by the garbage collector.
