### ISSUE TITLE
File realm/util/optional.hpp missing 

### ISSUE THREAD

**Issue by xavieramoros** [realm/realm-js#1430]
I'm trying to build Realm JS 2.0.1 using:
-iOS simulator
-XCode 9.0
-react native 0.48.4 

and I get this compile error:

![image](https://user-images.githubusercontent.com/347030/31936029-af891ce4-b8b0-11e7-8974-6224a318270b.png)

The file realm/util/optional.hpp is apparently missing?

![image](https://user-images.githubusercontent.com/347030/31936214-3a09945c-b8b1-11e7-902f-039026ad8304.png)

![image](https://user-images.githubusercontent.com/347030/31936119-f4b7fa4c-b8b0-11e7-8373-e6851bfeb882.png)

I was using RealmJS 1.13 and everything was fine.

**Comment by kneth** [comment]
Did you run `scripts/download-realm.js`?

**Comment by xavieramoros** [comment]
I didn't run this script, why should I? I just installed realm 2.0.1 via npm, aren't these scripts run automatically on install? 

I have downgraded to 1.13 so far, I thought it might be an issue with the new version.

My question looks like a duplicate of #1427, I totally missed it sorry.

**Comment by kneth** [comment]
No, you shouldn't run the script when you install via npm. We need to investigate it to see what is wrong with the latest release.

**Comment by xavieramoros** [comment]
Ok thanks for the quick reply!

**Comment by rh389** [comment]
@kneth It might not be broken as such but the `download-realm.js` build phase is just a bit fragile - to network interruptions, node environment changes etc. 

That's compounded by the fact that a) people don't expect building to require a download and b) the script (currently) exits with `0` even on error, so Xcode ploughs on with the build and the eventual failure appears very cryptic if you don't realise where those files should be coming from.

Ideally those vendor sources/binaries should be pulled in by yarn/npm as a postinstall step (if not packaged), but I realise it's tricky because you don't know at that stage whether people even need mobile binaries, and they'd be an enormous waste of space if you're using node. 

IMO it's always going to be awkward to cater for node and react native with the exact same package. Maybe if we had `realm-node` and `realm-react-native` which depend on this package and could also pull in more targeted dependencies where appropriate that might simplify things.

**Comment by kneth** [comment]
A good estimate is that 95 % of the source code is shared between all platforms. So for us, we just support JavaScript 😈  - and we use the one package only.

**Comment by rh389** [comment]
Sure, but separate packages could each depend on the common js core, there’d be no need for duplication. Just gives you an opportunity to deal with the 5% cleanly, and pull the right dependencies at install time. RN and node are quite different beasts for anything that goes as deep as realm.

Just my 2c, good luck either way!

**Comment by kneth** [comment]
@rh389 I appreciate the input :-) I was only explaining why we have a simple package. Making `download-realm.js` less fragile is a good place to start.

**Comment by kneth** [comment]
Version 2.1.0 should have improved the situation.
