### ISSUE TITLE
Parent Child Relationship, Delete & create child "bug"

### ISSUE THREAD

**Issue by PvanHengel** [realm/realm-js#1632]
## Goals

When using two related objects, eg "Parent" -> "Child" relationship, you should be able to delete the children object by primary key, and re-create it with the same primary key, and have the relationship remain. 

## Expected Results

When inserting a Parent Record with a Child Record P->C where the child record has a primary key of 123, when re-inserting the child record, with the same primary key, the Parent record should reference the new record.

## Actual Results

After deleting the child record 123, and inserting a new child record with the same primary key of 123, the parent record references an undefined object.

## Steps to Reproduce

1. Insert a child record with pk of 123
2. Insert a parent record with a reference to the child object
3. Retrieve the parent record, and check the child object
4. Delete the child record
5. Insert a new child record with the same primary key (123)
6. Retrieve the parent record, and check the child object, it will return undefined

## Code Sample

See the steps above, easy to re-produce.

## Version of Realm and Tooling

 "realm": "^2.1.0"

**Comment by kneth** [comment]
Deleting the child object will update the parent object (deleting the link). Realm stores a reference to the object and not the primary key. So what you describe is the expected behaviour.

**Comment by hashimmm** [comment]
Can this be made clear in the documentation? Especially since realm.io makes comparisons to sqlite. This is completely unexpected and counterintuitive. Might be a good idea to explicitly say so at least in the "relationships" section in the documentation here: https://realm.io/docs/javascript/latest/#relationships

**Comment by astigsen** [comment]
Instead of deleting and then recreating the object, you can update the object in place. You can do that even if you don't have an explicit reference to the object by using the `Realm.create()` method, setting `update=true`:

```javascript
realm.create('Child', {pk: 123, property1: 'new value'}, true);
```

This will update the object in-place, and retain all links to it.

**Comment by taqi457** [comment]
@astigsen, I get what you are saying, but what if I do want to delete all objects that no longer have any reference? 
Correct me if I am wrong, either I check all the parents and see if they have any reference for any of the children or never delete the children objects and just keep updating them.
I think it should throw an error if it is referenced somewhere. 
One way could be to define property on model like onDelete so that I can specify such behavior.
Another way might be having default error and an extra param on delete function to force delete regardless of references.
Plus I also think it was very confusing in document, the direct object relationship is not well defined in it. Specially coming from a RDMS background, the only place that clarifies it to some extent is on the academy: https://academy.realm.io/posts/realm-primary-keys-tutorial/
Maybe add this on the website itself?

**Comment by kneth** [comment]
@taqi457 We are currently working on cascading delete but it is a bit complicated when Realm Platform is involved. I hope that we have something to try soon.

**Comment by pedrosimao** [comment]
@kneth any news about cascading delete? This would be a highly appreciable feature.

**Comment by kneth** [comment]
Cascading deletes is more a core feature: https://github.com/realm/realm-core/issues/746
