### ISSUE TITLE
Can not download realm-sync-cocoa

### ISSUE THREAD

**Issue by kk412027247** [realm/realm-js#1645]
When i run 'react-native run-ios' after run 'yarn add realm'.
I can't download the 'realm-sync-cocoa-2.2.9.tar.gz'  file.

Stop in this screen for more then 1 hour. ⬇️⬇️⬇️
<img width="577" alt="2018-01-30 5 30 30" src="https://user-images.githubusercontent.com/30715186/35558567-55194bb4-05e3-11e8-90cc-3264c71c4484.png">

When i ping static.realm.io, i can get the request,  although the speed is slow.⬇️⬇️⬇️
<img width="577" alt="2018-01-30 5 34 17" src="https://user-images.githubusercontent.com/30715186/35558783-dc267e10-05e3-11e8-8b6f-41e455298e25.png">

Need some help.

**Comment by kneth** [comment]
@kk412027247 I can download it just fine: `curl https://static.realm.io/downloads/sync/realm-sync-cocoa-2.2.9.tar.gz -O`

As Realm contains encryption technology, your IP address might be blocked due to export regulations. Moreover, we have seen that some countries block access to Amazon S3 (which is hosting `static.realm.io`).

**Comment by kk412027247** [comment]
@kneth Can I download this file 'realm-sync-cocoa' on the other way, and then copy to the react-native project ?

**Comment by kneth** [comment]
@kk412027247 You are welcome to contribute any enhancements as a pull request :-)

**Comment by MujtabaFR** [comment]
@kk412027247 You saved my day,
I found The corrupted file in `/var/folders/7q/90mfr6bd4k565n7ynbldkxzh0000gn/T/realm-sync-cocoa-3.5.6.tar.gz` and replaced it with a better one.
Then editing the file you mentioned solved my problem
