### ISSUE TITLE
Get Length Of List

### ISSUE THREAD

**Issue by jeprojects** [realm/realm-js#1692]
## Goals

Get the count/length of a Realm List

## Actual Results

Undefined is not an object

## Steps to Reproduce

```
Meta.schema = {
  name: 'Meta',
  primaryKey: 'id',
  properties: {
    id: 'string',
    fileData: 'FileData[]'
  }
}

let meta = realm.objects('Meta').filtered('id = $0', '123')
let fileData = meta.fileData

console.log(fileData.length) // should output an integer 
```

## Version of Realm and Tooling

- Realm JS SDK Version: Latest
- Node or React Native: Latest React Native
- Client OS & Version: iOS
- Which debugger for React Native: ?/None

**Comment by bdash** [comment]
`realm.objects('Meta').filtered('id = $0', '123')` returns a _collection_ of objects that match the given predicate. When you're doing:
```js
let meta = realm.objects('Meta').filtered('id = $0', '123')
let fileData = meta.fileData
```

You're asking for the `fileData` property on this collection, which isn't a property that exists. What you'd want to do instead is to retrieve an element from the collection, then access its `fileData` property.

Or since `id` is your primary key you could just take the more direct route and use `Realm.objectForPrimaryKey`:
```js
let meta = realm.objectForPrimaryKey('Meta', '123')
```
