### ISSUE TITLE
Error when opening synced realm with current user while offline

### ISSUE THREAD

**Issue by thebnich** [realm/realm-js#1728]
Steps:
1. Log into ROS and get a `User`.
2. Open a synced realm with this `User`.
3. Shut down the ROS.
4. Restart the app.
5. Try to open the same realm with the `User` from step 1.

After after these steps, opening the realm (using `new Realm(config)`) succeeds, but throws a "Network request failed" error shortly after (this is a React Native red box error and isn't even catchable with a `try`/`catch` around the `Realm` instantiation).

Code:
```
export default class App extends Component<Props> {
  constructor() {
    super();
    this.logIn();
  }

  async logIn() {
    let user = Realm.Sync.User.current;

    if (!user) {
      user = await Realm.Sync.User.login(LOGIN_URL, 'test', 'test');
    }

    const config = {
      sync: {
        user,
        url: REALM_URL,
      },
      schema: [],
    };

    const realm = new Realm(config);
  };
}
```

System:
- Realm JS SDK Version: 2.3.3
- Node or React Native: React Native 0.54.2
- Client OS & Version: iOS
- Which debugger for React Native: None

**Comment by thebnich** [comment]
When offline, this [`performFetch`](https://github.com/realm/realm-js/blob/master/lib/user-methods.js#L185) when refreshing the token fails, as expected. This calls `print_error`, creating a red box React Native error because of the [`console.error`](https://github.com/realm/realm-js/blob/master/lib/user-methods.js#L95).

Can access token refresh errors be downgraded to `console.log` or even `console.debug` since this is an expected failure case for offline access?

**Comment by kneth** [comment]
@thebnich Thanks for the suggest (the second comment).

**Comment by gonza-lito** [comment]
Hi!! is there any work going on this?? if not I might try to take a stab a it, any suggestion??

**Comment by kneth** [comment]
@gonza-lito No progress yet. What do you wish to take a stab at?

**Comment by gonza-lito** [comment]
hi @kneth , so for what I understand, the problem is this line right here:
https://github.com/realm/realm-js/blob/2490d80d65782403a63d5638cd421d43737cf01f/lib/user-methods.js#L326

It fails with an error that is pretty visible, and for the case in question it would be nice to have a way to fail grafully since there's no connection available, allowing for the error to be dismissed by the user or handled elsewhere.

My first idea, is to throw that error up in the stack so that it can handled by whoever is calling refreshAccessToken, but I think i'm lacking some context over this.

Another more simple approach is to just remove the console for a log tool so that we can ignore the error message.

**Comment by kneth** [comment]
@gonza-lito `print_error()` is using `console.error` which is probably bad practice on RN (while it is fine for node.js). And maybe throwing in https://github.com/realm/realm-js/blob/master/lib/user-methods.js#L100 isn't the best idea.
