### ISSUE TITLE
Is it possible to add a switch to control "callbacks_poll"? The infinite loop of "callbacks_poll" causes me to not debug properly

### ISSUE THREAD

**Issue by TrustDec** [realm/realm-js#1783]
## Goals

Add a switch to control it
## Expected Results

Add a switch to control it
## Actual Results

Can I provide a switch to control it? The infinite loop of "callbacks_poll" causes me to not debug properly

Thread 1: EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)

## Steps to Reproduce
An infinite loop of callbacks_poll even if not used

## Code Sample
```
const realm = new Realm({ schema: [RecentMessageSchema] });
export const getKeyWordStorage = realm.objects(USERMESSAGE);

export const addInTheSpecifiedDataSource = (databaseTableName,data) => {
    realm.write(() => {
        realm.create(databaseTableName,data,true)
        //console.log(item)
    });
}
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.4.0
- Node or React Native: 0.55.3
- Client OS & Version: ?Mac OS 10.13.4
- Which debugger for React Native: ?React-Native-Debugger or Chrome

**Comment by kneth** [comment]
A pull request will be welcomed! Not sure where to add such a switch or flag - maybe in the configuration (as `_disableCallbackPoll`)?

**Comment by pedrosimao** [comment]
Any news on that, the callback requests are really annoying.

**Comment by kneth** [comment]
Not really. I have been sidetracked on other bug fixes and projects recently.

**Comment by pedrosimao** [comment]
@kneth I think this issue is related to ExpoKit... I am trying to eject ExpoKit now to see if it works.

**Comment by rafaelcamaram** [comment]
I don't think this issue is related to Expo, since I'm facing with it even without Expo :/

**Comment by DAfanasyev** [comment]
Hi,

I'm facing same issue. Application is very slow when debugging is on because of callbacks_poll requests.

It is possible to fix it with patch-package:
* install patch-package
* remove realm from node_modules, then run npm install (to get clean realm in node_modules, ./gradlew clean probably also will work, but I haven't tried)
* set bigger polling interval for pollTimeoutId in node_modules/realm/lib/browser/rpc.js
* run yarn patch-package realm

But patching node_modules doesn't sound like a good idea to me so would be really nice to have configuration option.

**Comment by TrustDec** [comment]
我已经收到你的邮件啦~,表着急,待我仔细查看
