### ISSUE TITLE
App freezes on querying objects in separate class

### ISSUE THREAD

**Issue by donni106** [realm/realm-js#1786]
My app runs smoothly before querying data.

I want to query an object with a simple filter:

```
realm.objects('Person').filtered('name != $0', null)
```

This is called in a class method:

```
import realm from '../realm';

class DBService {
  people() {
    return realm.objects('Person').filtered('name != $0', null);
  }
}
```

I can ask for the length and get the correct result. But my app stops working and do not respond anymore:

```
...
this.DBService = new DBService();
...
console.log('people', this.DBService.people().length); // this runs
const people = this.DBService.people();
console.log('people', people.length); // this runs
return people;
```

I can see the `console.log`s but the app freezes and I cannot do anything from now on.

When I change it to a simple array without doing realm stuff, my app is working as expected.

```
...
this.DBService = new DBService();
...
// console.log('people', this.DBService.people().length);
// const people = this.DBService.people();
const people = ['first', 'second', 'third'];
console.log('people', people.length); // this runs
return people;
```

Where have I forgotten something or what am I still missing?

## Version of Realm and Tooling

- Realm JS SDK Version: 2.4.0
- Node or React Native: React Native
- Client OS & Version: macOS 10.13.4

**Comment by kneth** [comment]
Does it happen on Android or iOS? Only when debugging?

**Comment by kneth** [comment]
I am trying to understand what goes wrong (or where our bug is). So, can you try the following two things:

1. Don't call `filtered()`
2. Use another value than `null` in the predicate

**Comment by kneth** [comment]
Sorry for the late reply. Realm JS 2.4.1 contains a fix similar to your issue (actually https://github.com/realm/realm-core/pull/3037) but upgrading to 2.6.0 should have solve it.

@ironage Do you know of any issues querying with `null`?

**Comment by ironage** [comment]
Hi @donni106 if the length of the results is correct then the query has run successfully. If you like you could even inspect which objects are returned to you before returning. The null queries you are doing will have worked even prior to js 2.6.0 (the fix was for a different null case mostly affecting iOS users using NSPredicate).

Since the query runs, it appears to be a problem with the lifetime of the objects. I can see that you are creating a `new DBService()`  and trying to return the results outside the scope of the `DBService`. With realm, the results are live and point into the realm file, so you need to have the realm accessible after you return the results. You can check [our documentation](https://realm.io/docs/javascript/latest/#auto-updating-results) to learn more about this. It will require that you change the architecture of your app a bit.

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.

**Comment by villemuittari** [comment]
I can confirm the freezing issue. We are developing an app which has Mapbox map. While moving on the map we fetch data from Realm. I noticed that making even a simplest query to Realm (fetching a single indexed record) freezes the map for a very small moment. We see the same side effect not just in map but even in a simple screens which has buttons where button become unresponsive. Hope you guys take the problem seriously.

I'm using @realm/react@0.6.2
