### ISSUE TITLE
SSL related issue when running on Linux + Electron

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1864]
## Actual Results

I see this in the main process when running Studio 2.2.0:

```
/tmp/.mount_instal7w6CmU/app/realm-stu: symbol lookup error: /tmp/.org.chromium.Chromium.t4Fezq: undefined symbol: SSL_get0_param
```

## Steps to Reproduce

- Start an Ubuntu 16.04 box
- Download Studio 2.2.0 from https://studio-releases.realm.io/v2.2.0/download/linux-appimage
- Change permissions to allow the AppImage to be executed
- Execute Studio it from a terminal
- Connect to a server Realm to observe the error in the terminal from which Studio was launched

## Code Sample

N/A

## Version of Realm and Tooling

- Realm JS SDK Version: 2.6.0
- Node or React Native: Electron
- Client OS & Version: Ubuntu 16.04
- Which debugger for React Native: N/A

**Comment by kraenhansen** [comment]
@emanuelez ☝️huh? Why does the bot say that?

**Comment by emanuelez** [comment]
Fixed

**Comment by kneth** [comment]
Realm JS 2.2.14 is the last version we know that Electron+SSL is working.

**Comment by kraenhansen** [comment]
Unfortunately this issue persists in Realm JS 2.13.0.

**Comment by kneth** [comment]
@fealebenpae Can you take a look?

**Comment by kraenhansen** [comment]
I have started an attempt at improving the test harness to be able to run the same tests in multiple environments.

**Comment by fealebenpae** [comment]
I’ve investigated the issue and it turns out that OpenSSL is correctly linked statically, but it’s an older version. Because we build realm-js on CentOS 6.1 (in order to support old enough Glibc versions) we also link against that distribution’s OpenSSL which is 1.0.1, while the realm-sync static library uses APIs introduced in OpenSSL 1.0.2, hence the missing symbol errors. I’ll try to get the Dockerfile to build OpenSSL 1.0.2k so we can link against that, but it was really unfortunate that realm-sync upgraded to an OpenSSL version not available on one of our supported systems.

**Comment by dev-zetta** [comment]
This is still a problem. Today I've upgraded my app to use latest version of realm-js and I got same error. After 4 hours of trying to fix this issue, i.e. why the realm cannot find the openssl's shared libs, I found this issue. After compiling and installing OpenSSL v1.0.2r and rebuilding realm-js from sources, it got solved.

**Comment by kneth** [comment]
@dev-zetta Which version of Realm JS did you experience the issue with?

**Comment by dev-zetta** [comment]
I'm using the latest version: 2.28.0.

**Comment by dev-zetta** [comment]
It doesnt work with OpenSSL 1.0.1. It compiles, but when you run the electron app, it will cause undefined symbol: SSL_library_init error. Thanks to fealebenpae for finding the cause of this problem.
