### ISSUE TITLE
Confused with the license

### ISSUE THREAD

**Issue by hyandell** [realm/realm-js#1987]
Hi Realm folk,

I was looking at the README which says "Realm JS is published under the Apache 2.0 license. Realm Core is also published under the Apache 2.0 license and is available here. "

When I look at the LICENSE file it also has a section regarding "REALM COMPONENTS - This software contains components with separate copyright and license terms". This appears to have been added to realm-cocoa to match 'core licensing' in 2014, but in 2016 it was removed from realm-core.

Could you help me understand if that text applies to realm-js and which components it applies to?

Thanks.

**Comment by hyandell** [comment]
Any thoughts?

**Comment by bmunkholm** [comment]
Sorry @hyandell for the late response.
All our SDKs (realm-js, realm-cocoa, realm-java, realm-dotnet) and realm-core are open sourced under Apache 2.0 in the form they are provided on github. realm-core wasn't originally open sourced, so therefore the change you noticed. So basically all the source code you find on github uses Apache 2.0 license as noted in the respective repos.
The synchonisation component that enables sync to Realm Cloud and Realm Object Server is not open sourced and is referred to as the "Realm Platform Extentions" in the license. It's provided in binary form and has the license described in LICENSE.
Hope this helps, otherwise let me know if it's still unclear.

**Comment by hyandell** [comment]
Thanks Brian.

So the following GitHub repositories should not contain the binary-only language (section 2) in their license file?

https://github.com/realm/realm-js/blob/master/LICENSE
https://github.com/realm/realm-cocoa/blob/master/LICENSE
https://github.com/realm/realm-java/blob/master/LICENSE
https://github.com/realm/realm-dotnet/blob/master/license.txt

**Comment by bmunkholm** [comment]
@hyandell Yes they should. That refers to the "Realm Platform Extensions" which is the binary sync component included in most of the SDK releases. Java can also be released without sync and it's a separate add-on module.

Could you elaborate your concerns if any?

**Comment by hyandell** [comment]
Thanks Brian.

I'm trying to identify the SDK without the binary licensed component. Is there a file inside the SDK code that is the binary, is it a separate download, is it the objectstore git module? What would I delete to turn the SDK licensing into the same thing as the Core licensing?

**Comment by bmunkholm** [comment]
@hyandell I'm afraid that realm-js doesn't come released without the sync component. You would have to fork the project and fix the build files to not use the binary that is _downloaded_. Unfortunately, the API's are not designed to exclude the sync APIs so that would be needed to get separated out as well.
Sorry it doesn't exactly seem trivial. 
What's your concern though with the binary? Which limitations does it impose on your use?

**Comment by hyandell** [comment]
It means treating the Realm SDKs as not open source. I'd prefer to be able to point to them and say "They are open source" or "They are open source as long as you delete ./sync/binary.dll". As it is, an undefined chunk of the code is binary-only so the whole have to be considered as proprietary :(

I'm not saying that the proprietary license is a problem/bad (depends on situation I imagine), but it's non-standard which adds complexity. The README's also not very clear; it says the SDK is Apache 2.0 (plus export statement).

**Comment by hyandell** [comment]
I've proposed a clarification for the README in #2056
