### ISSUE TITLE
Explain better how to use Object Permissions

### ISSUE THREAD

**Issue by apperside** [realm/realm-js#2010]
Hi,
I am trying to work around with lastet fine graded permssions api, and I am experiencing both some problem to use it and some difficoulty to undesrtand how it works beacause of the lack of clear documentation.

## Goals

Understand how the permissions api work

## Expected Results

Easly use permission api without issues

## Actual Results

Before trying to work with the permission api, I am trying to achieve the most basic task: create some objects and read them.

Here are the most relevant parts of the code:

I have this class 

```
class MyObject {
 static schema = {
        name: 'myobject',
        primaryKey: 'uuid',
        properties: {
            uuid: { type: "string" },
            name: 'string',
            permissions: '__Permission[]'
        }
    }

uuid:string=""
name:string=""

}
```

I open the realm in this way

 ```
let PUBLIC_REALM_CONFIG: Realm.Configuration | undefined = undefined

                try {
                    PUBLIC_REALM_CONFIG = Realm.Sync.User.current.createConfiguration({
                        schemaVersion: 1,
                        schema: [MyObject.schema]
                    });
                     return Realm.open(config)
                     .then((realm) => {
                          return realm
                     })
                } catch (error) {
                    console.error("error openging realm", error)
return null
                }

```
Then everytime the app starts, I run this code

```
realm.write(async () => {
                    let obj = new MyObject()
                    obj.uuid = randomUuid()
                    obj.name = "test"
                    realm.create(MyObject.schema.name, obj)
                })
                let items = await realm.objects<MyObject>(MyObject.schema.name)
                console.warn("there are "+ items.length+" items");
```
The result of this is that: 

- I see that everytime a new item is created in realm studio, but the log always prints "there are 1 items"
- If, starting from an empty table and commenting the code which creates a new item, I create an item manually in realm studio, the log says "there are 0 items". So here a question rises: what should I do in order to manually create data inside realm studio?

**NOTE:The problem happens in both react native and node**

I used the same code using a previous version of realm and not using reference realms

## Version of Realm and Tooling

- Realm JS SDK Version: 2.15.3
- Node or React Native: node version: 9.10.1 , react native version:0.52

**Comment by bmunkholm** [comment]
@apperside I've updated the title to better reflect what I think you would like us to do?
We realize we haven't done a good enough job of this yet and aim to correct this now. It would be wonderful if you could help us better understand what in general is unclear (besides your specific question above). Are there other specific areas in the docs you would like us to make better (around permissions)?

**Comment by bmunkholm** [comment]
@apperside ok - yeah I didn't look much at the code. Only the text you had written.
We try to keep github for bugs or feature requests and otherwise redirect usage questions to our Forum or StackOverflow where you often get quick help. 
That said a few hints: Our API is synchronous. So it doens't make sense to pass an async function to write(). Also realm.objects() is not an async function. You have to setup a progress notification to wait for the data to sync from the server to your app. Please check the docs and samples to see how to do that.
Once that's fixed please do create another issue about how the permission docs could be improved. Your feedback would be very appreciated! Thanks!

**Comment by nirinchev** [comment]
@apperside the problem is that you're using query-based sync and you have no subscriptions defined in your app. That's why you're seeing only the locally created changes and only briefly - the next time you run the app and it syncs to the server, it will notice that the local changes are not requested so it will delete them (but they'll remain on the server). Please, check out the [docs for query-based sync](https://docs.realm.io/platform/using-synced-realms/syncing-data#using-query-based-synchronization) for more info on how to use it.

**Comment by apperside** [comment]
Thank you so much @nirinchev !!
That helped my a lot, I didn't well understood how query based synchronized realms work.
Adding this worked perfectly:

```
items.subscribe() //<-- this is the most important
items.addListener(async (callback) => {
    console.warn("data changed", callback)
})
```

In the listener I always have the up to date data.

But this leads me to one more question: so on this type of realms I can't be sure that I always have the last data just after calling realm.objects("class_name") right? I always need to work with data inside the listener right?

Thanks again

**Comment by apperside** [comment]
@bmunkholm I created the #2011 issue where I explain how I think the docs can be improved

**Comment by nirinchev** [comment]
Not sure I understand correctly, but there's no difference between full and query-based synchronization in terms of "making sure you have the last data". Once you create a subscription, this will be kept up to date automatically and new data will flow as it becomes available on the remote Realm. The only difference is that you explicitly specify which objects you want synchronized. And if you want to know when the initial data load has completed, you can add listener to the subscription object:

```js
const subscription = items.subscribe();
subscription.addListener((sub, state) {
  if (state === Realm.Sync.SubscriptionState.Complete) {
    console.warn("Initial load complete...");
  }
});
```
