### ISSUE TITLE
Saving object with random keys directly as Realm object

### ISSUE THREAD

**Issue by abrarum** [realm/realm-js#2039]
## Goals
Want to save an object with random keys and value, let's say:
{btc: 0.10, eth: 0.001, sbg: 10.11, xcc: 0.9}

Saving it directly into the realm as object.

## Expected Results
Expecting a realm object in a schema to directly save an object like above so that it could be easily accessed as a property object from realm.

## Actual Results
In actuality and as the realm doc says that its necessary to create a child schema to inject objects with a static key like:

Schema DATA = {coinName: string, value: float}
Schema API = {exchangeName: string, coinData: DATA[ ] }

## Code Sample

Here is the actual code example:

```
class CryptoDataSchema extends Realm.Object { }

CryptoDataSchema.schema = {

    name: 'CryptoData',
    properties: {
        cryptoName: 'string',
        value: 'float',
        link: 'string'
    }
};

class AddExchangeSchema extends Realm.Object { }

AddExchangeSchema.schema = {

    name: 'AddExchange',
    properties: {
        selectExchange: 'string',
        apikey: 'string',
        secretkey: 'string',
        logoLink: 'string',
        balance_final: 'CryptoData[]'/* 'CryptoData[]' */
    }
}

realmIt(exchange_data) {
        realm.write(() => {
            const ExchangeIns = realm.create('AddExchange', {
                selectExchange: this.state.selectExchange,
                apikey: this.state.apikey,
                secretkey: this.state.secretkey,
                logoLink: exchange_data.logoLink,
                balance_final: [] /* "Exchange is overhaul by dry winds.." */,
            });

            _.map(exchange_data.balance_final, (val, key) => { ExchangeIns.balance_final.push({ cryptoName: key, value: val, link: `../../node_modules/cryptocurrency-icons/32/color/${key}.png` }) });
        });
        /* this.props.navigation.navigate('BottomTabsDashboard'); */
        /* console.log(realm.objects('AddExchange')); */
    }
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.14.2
- Node or React Native: 0.55.4
- Client OS & Version: Windows 10
- Which debugger for React Native: Chrome dev

**Comment by kneth** [comment]
The answer in https://stackoverflow.com/questions/50504485/how-to-store-array-of-objects-in-realm-js/50508158#50508158 outlines how to work with list.

**Comment by c100k** [comment]
@kneth Sorry I know this has been closed but I've landed here via Google. I think the issue of @abrarum is more about storing objects instead of lists. As an example, how would it be possible to store something like:

```js
{
    id: 123,
    name: 'Toto',
    metadata: {
        randomKey: '--',
        anotherRandomKey: ['one', 'two']
    }
}
```

The [data types](https://docs.mongodb.com/realm/sdk/node/data-types/field-types/) for `id` and `name` are pretty obvious. But what about the type of `metadata`. Going with `dictionary` doesn't work because the values can be anything (nested object, array, etc.).

The only workaround I've found right now is to store a "stringified" version of the object, and therefore use `string`. Is there something else better that we would have missed ? (something similar to Postgres' `json` for example).

Thanks in advance.
