### ISSUE TITLE
Disable debug mode only for Realm in React Native?

### ISSUE THREAD

**Issue by csotiriou** [realm/realm-js#2070]
I am trying to use Realm in my application. Since this issue exists and will not be fixed for the foreseeable future (https://github.com/realm/realm-js/issues/491), I am not able to put debug debug mode in React Native and I am searching for a way to debug the rest of the application. Note that the data I need to store is really big.

Is there a way either on iOS or Android to disable debug mode only on Realm, but still keep debugging the rest of the application using the chrome debugger?

I have tried debugging using Reactotron logs or any other method, but not being able to put a breakpoint in my application is really bad.

**Comment by esutton** [comment]
@csotiriou A disable debug feature is badly needed.

I will be replacing Realm Js with TypeORM & SQLite3.  The ONLY reason I am doing this extra work is because of the impact Realm JS has on debugging React Native apps.  

Waiting for potential architectural changes by the React Native / Facebook core developers is not an option.

**Comment by sambwest** [comment]
@esutton have you tried using safari to debug instead? I actually prefer it and there isn't any performance penalty as the code is ran on the device, not the browser (like chrome).

**Comment by csotiriou** [comment]
@sambwest the JS bundle is minified in safari. There are no source maps there. There are also no redux dev tools or react dev tools.

**Comment by sambwest** [comment]
@csotiriou sure - not disputing it, just offering an alternative. I moved away from chrome not because of the performance (it doesn't affect me) but because 90% of the bugs I find with this library are due to the debugger in chrome. It behaves strangely in a number of ways.  The bugs don't get fixed very quickly so it's a struggle for it not to effect development, hence my side step to safari.  I would obviously welcome this if it were possible.

**Comment by esutton** [comment]
@sambwest I did not get far with Safari.  

Safari debug seemed extremely primitive of limited value compared to Chrome debug.  I did not see value in using Safari probably for reasons @sambwest stated:

> the JS bundle is minified in safari. There are no source maps there. There are also no redux dev tools nor react dev tools...

A ````realm.debugEnable```` method to turn off all the Realm chatter, would enable debugging of a React Native application that was unfortunately tied to using Realm Js.

**Comment by esutton** [comment]
@dlimx Any luck with any dirty work-arounds?  

If so, **please** make a fork.  I am sure many could benefit.  

There is no guarantee that Facebook's multi-year long process of rearchitecting React Native will have any benefit to solving Realm's debugging performance problems.  This affects debugging on all React Native apps that use Realm JS.

**Comment by dlimx** [comment]
@esutton based on comments by the Realm team, we're just waiting for 0.58. I didn't find anything quick to exclude realm - so unless you don't need realm data for your current feature...

**Comment by kneth** [comment]
If the improvements introduced in v2.28.0 has helped, we can reopen the issue.
