### ISSUE TITLE
Error: mmap() failed (size: 1456, offset: 0: Invalid argument     at Object.<anonymous>

### ISSUE THREAD

**Issue by jlubeck** [realm/realm-js#2217]
## Goals

Just initialize Realm

## Expected Results

My app not to crash

## Actual Results

```
/media/sf_shared/tempguard.1.0/usr/lib/node_modules/realm/lib/index.js:152
    realmConstructor.Sync._initializeSyncManager(createUserAgentDescription());
                          ^

Error: mmap() failed (size: 1456, offset: 0: Invalid argument
    at Object.<anonymous> (/media/sf_shared/tempguard.1.0/usr/lib/node_modules/realm/lib/index.js:152:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/media/sf_shared/tempguard.1.0/usr/lib/index.js:8:15)
    at Module._compile (module.js:652:30)

```

## Steps to Reproduce

This is happening on an Ubuntu 18.04 machine.
It's working fine on macOS.
Line 8 of index.js is just this:

`const Realm = require('realm');`

## Code Sample

`const Realm = require('realm');`

## Version of Realm and Tooling

- Realm JS SDK Version: realm@2.20.1
- Node or React Native: Node v8.10.0
- Client OS & Version: Ubuntu 18.04
- Which debugger for React Native: ?/None

**Comment by jlubeck** [comment]
Just tried downgrading node to 6.11.5 (which was the version of node that works on macOS) but still getting the same error

**Comment by jlubeck** [comment]
Thanks for the quick response! I can't check that command right now (don't have access to it until tomorrow), but I can tell you that `sf_shared` is a virtual box shared folder between the VM (where I'm running Ubuntu) and the host (macOS).

This share has full write access though. And I've been using it for other projects without issues.

I'll make sure to put the output of that command here tomorrow. And I'm also going to try running the app on a non-shared disk to see if something changes.

Thanks again!

**Comment by finnschiermer** [comment]
I think, this is a problem with memory mapping the .lock file

You may get something from the last comment in this thread: https://www.virtualbox.org/ticket/819

**Comment by cmelchior** [comment]
Yes, this is a bug on our end. It is in the process of being fixed. I'll fold this issue into #2218

**Comment by jlubeck** [comment]
Nice to see the quick response on that new ticket and pull request.

@ironage I know this one is now closed, but since you asked, I just wanted to tell you that the page size of the system is 4096

Don't know if that helps or not. But didn't want that to go unanswered.
Thanks!

**Comment by ironage** [comment]
Thanks for the information @jlubeck. Issue #2218 can explain the immediate problem of failing on the import itself. But as @finnschiermer points out, there is another deeper issue here which you might encounter again if you try to open and write a Realm file on the shared file system. According to the thread referenced, there could be a problem with the virtual box drivers. @jlubeck is your Ubuntu running under virtual box? If you encounter the same error when you open a Realm file on the shared disk, please reopen the issue - if this is the case, you may have to store Realm files on a different (non shared) disk until we can find/fix the issue. If the problem is really related to virtual box, upgrading that software might fix the issue as well.
