### ISSUE TITLE
Impersonate another user when constructing `Results`

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#2272]
## Goals

Now that [sync has implemented an API to impersonate another user](https://github.com/realm/realm-sync/issues/2781) it would be great to get this API exposed through Realm JS.

Note: This feature is probably only relevant for an admin user which has opened a reference Realm.

I believe this should be exposed on the `Results` class, but perhaps it would be possible to add it on the `List` too and we could put the method on the `Collection` instead? I'm imagining an API where a new method is added to the `Results` class to get the results filtered by the permissions of another user:

---

## 1st API suggested

```typescript
interface Results<T> extends Collection<T> {
    /**
     * Query as a specific user, by applying fine-grained permissions to the elements of the result.
     * @param {string} userId The ID of the user which we want to apply permissions for.
     * @returns Results The results filtered by applying the fine-grained permissions.
     */
    as(userId: string): Results<T>;
}
```

### An example of usage could be

```typescript
const realm = new Realm({ ... });
const wines = realm.objects<IWine>("Wine");
const oldMerlots = wines.filtered('variety == "Merlot" && vintage <= $0', 2010);

const johnsUserId = "0a8dfebc-40b8-11e9-b210-d663bd873d93";
const johnsOldMerlots = oldMerlots.as(johnsUserId);
console.log(`John has access to ${johnsOldMerlots.length} old merlots.`);
```

---

## 2nd API suggested (by @nirinchev 👇)

```typescript
class Realm {
    /**
     * Create a user specific wrapper around the open Realm to perform queries as a specific user.
     * @param {string} userId The ID of the user which we want to apply permissions for.
     * @returns Realm A wrapper around the Realm instance which has modified behaviour to check fine-grained permissions when querying for and writing objects.
     */
    as(userId: string): Realm;
}
```

### An example of usage could be

```typescript
const realm = new Realm({ ... });
const johnsUserId = "0a8dfebc-40b8-11e9-b210-d663bd873d93";
const realmAsJohn = realm.as(johnsUserId);
const johnsWines = realmAsJohn.objects<IWine>("Wine");
const johnsOldMerlots = johnsWines.filtered('variety == "Merlot" && vintage <= $0', 2010);
console.log(`John has access to ${johnsOldMerlots.length} old merlots.`);
```

**Comment by nirinchev** [comment]
I would rather see an API where the entire Realm is opened as a particular user because that would then allow me to make write transactions that will supposedly be rejected due to permissions.

**Comment by kraenhansen** [comment]
As I can tell the API made available by sync is for queries, not write transactions - is that correct @ironage / @simonask?

From Studios perspective it's nice that it doesn't need to reopen the reference Realm when an admin wants to impersonate a specific user. Isn't that the same for the graphql service? If two users have queries against the same reference Realm it would be annoying to have to close and reopen the realm between the two requests?

**Comment by nirinchev** [comment]
Yes, we need another change in sync to facilitate impersonated write transactions. I was thinking more of wrapping the Realm into a thin js wrapper that replaces some methods with impersonated ones, so the Realm would be opened once as an admin user and then, you would call `const impersonate = realm.as('abc...')` which will return an object with the same API as `Realm` but will replace `.objects`, `.write`, `.objectForPrimaryKey` and so on with user versions.

**Comment by simonask** [comment]
Impersonation for modifications has to take place at the Object Store or SDK level. Or we will provide an API that wraps every Core function to modify the database, which is possible, but has basically the same or worse impact at the SDK level.

Writes are applies "as is" -- it is not the case that a transaction is generated and only then applied later locally, and that would also be a much worse experience (you would get the permission error at commit-time rather than where it actually happened).

"Impersonating" writes is equivalent to wrapping all modifications in code like the following:

```
if (perms.can(Privilege::Update, object)) {
    object.set(field, value);
} else {
    throw AccessDeniedError();
}
```

Either the SDKs implement a version of their APIs that can contain this logic, or Sync implements a set of APIs mirroring the entirety of Core, and requires bindings to call these all over the place. I prefer the former. :-)

**Comment by tgoyne** [comment]
Filtering a Results based on whether a given user can read the objects would require extending the core query system with that functionality. It's not really something that can be done at the SDK (or object store) level.

**Comment by ironage** [comment]
The query part is implemented by sync (https://github.com/realm/realm-sync/pull/2790) so that any query can be run with a specified user id: `realm::sync::query_with_permissions(Query query, StringData user_id, const DescriptorOrdering* ordering)`. With this, you do not need to reopen the Realm, you can have simultaneously the admin queries and the impersonated user queries. However, to impersonate modifications, it is probably a cleaner design to open the Realm file again as the other user, that way we would truly be impersonating the user rather than trying to mimic user operations via new code. On that point I agree with Nikola:

> I would rather see an API where the entire Realm is opened as a particular user because that would then allow me to make write transactions that will supposedly be rejected due to permissions.

**Comment by tgoyne** [comment]
Ah, that function almost does what is needed. The only change required is that it needs to produce the Query rather than the TableView resulting from find_all() on the Query.

Adding a mode where permissions are checked locally on the client when making modifications seems somewhat orthogonal to adding the ability to send impersonated writes to the server.

**Comment by kraenhansen** [comment]
> I was thinking more of wrapping the Realm into a thin js wrapper that replaces some methods with impersonated ones.

That would be an okay API from Studios needs too, but I envision that it might be a bit more complicated to implement?

**Comment by simonask** [comment]
> Ah, that function almost does what is needed. The only change required is that it needs to produce the Query rather than the TableView resulting from find_all() on the Query.

Should be super trivial to change, now that we actually express permission checks as queries.

The only difference between impersonating locally versus sending impersonated uploads to the server should be in cases where there is a permission conflict. If someone is changing the permissions on the server while someone else is making locally impersonated changes, those changes will go through regardless of the permissions on the server, whereas if we are impersonated uploads will be handled in the normal way in case of permission conflicts (first permissions to arrive on the server win).

**Comment by kraenhansen** [comment]
I believe this can safely be closed now and perhaps reopened once we get more clarity on what replaces query-based sync and client-side permissions.
