### ISSUE TITLE
Follow-up to adding a Podspec

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#2587]
Once https://github.com/realm/realm-js/pull/2586 merge, we still have a few outstanding changes to the codebase and docs:

- [x] Remove the hint about running “react-native link realm”.
- [x] Read CONTRIBUTING.md to ensure nothing is outdated and write https://github.com/realm/realm-js/blob/master/CONTRIBUTING.md#how-to-debug-react-native-podspec
- [x] Update docs to ensure it’s not mentioning running “react-native link realm”, including instructions to manually link.
- [ ] ~Run “pod lib lint --verbose” on CI (from node_modules/realm of a React Native app)~ As we `pod install` in the integration tests, this is probably not needed.
- [ ] Write about the caveats of the "use_frameworks!" support.
- [ ] Consider using a global to make Realm JS depend on the `React` framework, instead of reading the users Podfile (which is a hack).
- [ ] GCDWebServer is now a CocoaPod dependency and since Android uses [NanoHttpd](https://github.com/NanoHttpd/nanohttpd) we can remove the GCDWebServer submodule from the repository.
- [ ] Depend on a specific major version of GCDWebServer.
- [ ] Investigate if we could provide a way of building Realm JS with the debug version of the shared library.
- [ ] Update the example app by unlinking Realm JS.
- [ ] Setup an install test on CI (with and without `use_frameworks!` - see https://blog.cocoapods.org/CocoaPods-0.36/).

**Comment by ioveracker** [comment]
We're noticing that the RealmJS checksum in the `Podfile.lock` seems to be changing frequently even with `realm` pinned in `package.json`. Is this a known issue?

**Comment by kraenhansen** [comment]
@ioveracker No it's not - please open an issue 👍

**Comment by davidnuvolar** [comment]
This is also happening to us. I tried to create a sample project from scratch and it's not happening there.
Could it be related with this?
https://github.com/CocoaPods/CocoaPods/issues/8931

**Comment by ioveracker** [comment]
@davidnuvolar that looks promising! We're a minor version behind on CocoaPods. I'll test that out this week and report back.

**Comment by ioveracker** [comment]
Upgrading to CocoaPods 1.8.4 didn't change things for us. We're still getting RealmJS checksum diffs on different machines.

**Comment by davidnuvolar** [comment]
@ioveracker found the root cause of the issue! If you just care about the solution, upgrading your realm dependency to 3.6.0 should fix this. It was fix in this PR https://github.com/realm/realm-js/pull/2623/

If someone is curious and wants to know more:
**What is the checksum we see in the Podfile.lock?** It is just the SHA1 from the Podfile.lock.json
You can get the hash by running from the command line:
`cat /path/to/your/react-native/project/ios/Pods/Local\ Podspecs/RealmJS.podspec.json | openssl sha1`

So if different computers are producing different hashes, it means the content of that json file must be different. That's exactly what's happening here. In the Podspec from version 3.4.2, line 78, 
`"'#{app_path}/ios/Pods/Headers/Public/React-Core'"`
https://github.com/realm/realm-js/blob/6e28389898a6276459b95e1c861a4166e87a69d0/RealmJS.podspec#L78
the code generates an absolute path when building your local json podspec. Because of this, different computers with the project in different locations will generate different checksum for this pod.

In version 3.6.0 this has been changed to 
`'"$(PODS_ROOT)/Headers/Public/React-Core/"'`
 https://github.com/realm/realm-js/blob/13a6fc834a656c1d0551fea3ca82318aa61fb28e/RealmJS.podspec#L86
and now it uses an environment variable. Because of this, the checksum will match even if the location of the project is different.

**Comment by kraenhansen** [comment]
Awesome @davidnuvolar! Thanks for getting to the bottom of this, its a nice side-effect of not having absolute paths produced by the Podspec.

**Comment by ioveracker** [comment]
Yep, we're good to go. Thanks @davidnuvolar!
