### ISSUE TITLE
Method to wait for Realm.Sync.Subscription completion

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#2650]
## Goals

A more intuitive API, requiring less boilerplate code from developers.

## Expected Results

When creating a QBS subscription, the user of our API needs to add a listener and await a state transition to the "completed" state. We could help the user by providing a method, returning a promise which resolves when the state has transitioned to completed or reject (with the error message) if it transitions to an error state.

Ideally this would also take a timeout (as milliseconds) as a parameter, ensuring that the promise either resolves or eventually gets rejected. We should also not forget to remove any state change listeners that we register, before resolving or rejecting the promise.

### `await subscription.whenCompleted()`
Suggested at [an airbnb issue](https://github.com/airbnb/javascript/issues/848#issuecomment-322093859) with the most 👍 s.
**Pros:** 1) Makes somewhat sense when read alound. 2) Mentions the "completed" state that we're actually waiting for. 3) Felt like the strongest contestant between @kneth and I (@kraenhansen) and it was independently suggested by an JS developer external to the team.
**Cons:** Misalignment across SDKs.

### `await subscription.waitForSynchronization()`

Realm .NET has "[WaitForSynchronizationAsync"](https://realm.io/docs/dotnet/4.2.0/api/reference/Realms.Sync.Subscription-1.html#Realms_Sync_Subscription_1_WaitForSynchronizationAsync).
**Pros:** Alignment across SDKs.
**Cons:** 1) Code using this would be `await subscription.waitForSynchronization()`, which doesn't make too much sense when read aloud. 2) We are waiting for the subscription to "complete" not for it to "synchronization" (to the server).

### `await subscription.forCompletion()`
Suggested as an alternative naming convention [at the airbnb issue](https://github.com/airbnb/javascript/issues/848#issuecomment-517497847)
**Pros:** Makes somewhat sense when read aloud.
**Cons:** Misalignment across SDKs.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.5.0
- Node or React Native: N/A
- Client OS & Version: N/A
- Which debugger for React Native: N/A

**Comment by cmelchior** [comment]
Naming is hard 😄

In Java we have support for this through  `SyncSession.uploadAllLocalChanges()` and `SyncSession.downloadAllRemoteChanges()`. But that isn't exactly intuitive either in the context of subscriptions.

The wording is tricky though because `Complete` is a very internal word used by ObjectStore...it just means that the subscription has been processed by the server and is now actively synchronizing data. It never finishes, which is kinda what complete implies (to me).

So `ready`, `complete`, `synchronization` are all sort of correct without capturing it completely. Not sure if there is a word that does that without being overly verbose. Personally I probably like `ready` or `active` more.
 
With regard to JS, I would think that if `whenX` is a common naming pattern for promises that trumps trying to find a name across all SDK's.

**Comment by kraenhansen** [comment]
I'll close this for now, until we get clarity on the future of a replacement of query-based sync.

**Comment by mujehoxe** [comment]
Error: `waitForSynchronisation` resolved after the `subscriptions` went out of scope

**Comment by nirinchev** [comment]
@mujehoxe please open a new issue rather than commenting on a closed 3-year old one.
