### ISSUE TITLE
After delete object type, can't insert new objects

### ISSUE THREAD

**Issue by barak109** [realm/realm-js#2723]
## Goals

Deleting all old data of specific type and insert new data

## Expected Results

the new data will be Enter

## Actual Results

The data deleted and after i trying to insert new  data i'ts failed
I get
"accessing object of type Conversations which has been invalidated or deleted" 

## Steps to Reproduce

1.enter data all good  - work
2.delete all data of type  - work
3.insert new data to the type - doesn't work

## Code Sample

realm logic  -
```
export const enterConvs = async convs => {
  await Realm.open({
    schema: SchemasArray
  }).then(realm => {
    realm.write(() => {
      let newConvs = [];
      for (const conv of convs) {
        let isConvExist = realm
          .objects("Conversation")
          .filtered(`_id = "${conv._id}" LIMIT(1)`);
        if (!isConvExist[0]) {
          newConvs.push({...conv});
        } else {
          newConvs.push({...isConvExist[0]});
        }
      }
      const oldConvs = realm.objects("Conversation");
      realm.delete(oldConvs);
      for (const newconv of newConvs) {
    realm.create("Conversation", {newconv});
    }
    });
  });
};
```
Conversation.tsx
```

  componentDidMount() {
    listenToConvs().then(convs => {
      this.convsListener = convs;
      this.convsListener.addListener(() => {
        this.setState({convs: Array.from(convs)});
      });
    });
```

logic realm-
```
export const listenToConvs = () => {
  return Realm.open({
    schema: SchemasArray
  }).then(realm => {
    return realm.objects("Conversation");
  });
};

```

## Version of Realm and Tooling

- Realm JS SDK Version: 3.6.0
- Node or React Native: 0.59.8
- Client OS & Version:ios 13.3 and android 8
- Which debugger for React Native: chrome

**Comment by kraenhansen** [comment]
Your code is trying to create a new `Conversation` object from a deleted `Conversation` object, hence the error that you're seeing.

If I read your code correctly, you want to add all objects from `convs` which is not already in the realm?

Your code could be simplified and the error avoided as:

```javascript
export const enterConvs = async convs => {
  await Realm.open({
    schema: SchemasArray
  }).then(realm => {
    realm.write(() => {
      let newConvs = [];
      for (const conv of convs) {
        let isConvExist = realm
          .objects("Conversation")
          .filtered(`_id = "${conv._id}" LIMIT(1)`);
        if (!isConvExist[0]) {
          realm.create("Conversation", conv);
        }
      }
    });
  });
};
```

Also:
1. Consider using [`objectForPrimaryKey`](https://realm.io/docs/javascript/latest/api/Realm.html#objectForPrimaryKey) instead of filtered with a limit of 1, if your schema have `_id` as primary key.
2. The `updateMode` argument of the [`create`](https://realm.io/docs/javascript/latest/api/Realm.html#create) method is a good candidate for this use-case. If `"modified"` is passed in, it will update or create an object (and you don't need to check if it exists first).

I'm closing this as the behaviour is as expected (at least from our point-of-view 🙂).

**Comment by barak109** [comment]
> ```js
> realm.create("Conversation", conv, "modified");
> ```
Thank you 
But i want to sync my  "Conversation" to be as look like convs 
- if some conv delete in the server and i want to sync it and send to the client a new convs
* your solution doesn't show me how can i delete the old conv after syncing from the server
