### ISSUE TITLE
run object-store tests in realm-js ci

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#275]
Need to create an XCode target to run catch.hpp tests

http://hiltmon.com/blog/2014/10/26/simple-c-plus-plus-testing-with-catch-in-xcode/

**Comment by appden** [comment]
@alazier I see that `object-store` test case was added to `test.sh`. It fails for me on `brew install cmake` because I already have cmake installed. I don't think our test script should even try to install something "globally" anyways. Can we just remove that?

Also, while you're adding tinkering with this and adding it to Jenkins, can you add `eslint` and `jsdoc` tests to Jenkins as well?

**Comment by alazier** [comment]
once cmake is installed on the ci machines we can remove this.

**Comment by bdash** [comment]
CMake should be on the CI machines already as the object store uses it.

**Comment by alazier** [comment]
Yeah - just removed it from our script.
