### ISSUE TITLE
Could not new Realm in react-native project sometimes.

### ISSUE THREAD

**Issue by thuongtv-vn** [realm/realm-js#2760]
Hi All

I am having the issue when open the Realm database by "new Realm" on my react-native project.

Realm version: 2.28.1
React-native: 0.60.5

Sometimes, when I start my project and open my database by async function. In this function, I open the Realm database by the new operator. But the realm instance is null sometimes.

Do you have any ideas?

**Comment by kraenhansen** [comment]
Hi there,

In general, you're using a version of this package that was released June of last year, a lot of code has changed since then. Would it be possible for you to retry with the latest version of Realm?

That being said, it's very odd that the result of calling a constructor becomes `null`, we would have to see some code to help you debug this.

When opening a synced Realm from an async function, please also consider using the non-blocking Realm.open static method, which returns a promise that resolve when the Realm is fully downloaded.

**Comment by thuongtv-vn** [comment]
Hi @kraenhansen 
Thank you so much for your suggestion!

**Comment by kraenhansen** [comment]
Glad I could help - I'll close this for now, please reopen with some code if you keep on hitting this issue.
