### ISSUE TITLE
Instance method toJSON() missing from TS definitions

### ISSUE THREAD

**Issue by Dids** [realm/realm-js#2903]
## Goals

[Realm JS v5.0.0 release notes](https://github.com/realm/realm-js/releases/tag/v5.0.0) mention the `.toJSON()` instance method that should be available on all `Realm.Object` instances (as far as I can tell).

## Expected Results

I expect to be able to serialize Realm objects to a JSON string.

## Actual Results

`Realm.Object.toJSON()` does not exist, anywhere. Not in the API documentation, not in the sources.

## Steps to Reproduce

Query for Realm objects and attempt to serialize them.

## Code Sample

```js
for (const foo of realm.objects('Foo')) {
  console.log(foo.toJSON())
}
```

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.1
- Node or React Native: Node
- Client OS & Version: macOS 10.15.5
- Which debugger for React Native: None

**Comment by Dids** [comment]
Apparently `foo.keys()`and `foo.entries()` don't work either, even though the TS definitions are there (runtime exceptions for missing functions). Calling `Realm.Object.prototype.keys.call(foo)` does work however. I've yet to try this for `toJSON()`, as it was missing from the TS definitions entirely.

**Comment by Dids** [comment]
Eureka! This seems to work:
```js
(Realm.Object.prototype as any).toJSON.call(foo)
```

So I guess the real issue is just the missing TS definition for `toJSON()`?

**Comment by Dids** [comment]
While I'm at it, is `toJSON()` supposed to be recursive? Or does it only work at the top level?

**Comment by kneth** [comment]
@Dids It looks like an oversight from our side. No, `toJSON()` is not recursive. It is possible to construct cycles with Realm, which means that `toJSON()` will loop forever. The API documentation could be cleaner on that aspect too!

**Comment by Dids** [comment]
@kneth Thanks! Luckily I managed to make my own safe recursive serializer with the help of `toJSON()`.

Before I open a separate issue, are the changes made to the Realm JS change handler documented anywhere? Didn't see much in the release notes here and was wondering about several of the changes, including how the Realm objects referenced with each change event don't seem to have an `isValid()` method (or property) anymore?

**Comment by Dids** [comment]
@steffenagger Were `keys()` and `entries()` also fixed?

**Comment by steffenagger** [comment]
@Dids They should already be fixed in the latest patch-releases (no?). Please note that this `toJSON` declaration fix has not yet been released: [CHANGELOG](https://github.com/realm/realm-js/blob/master/CHANGELOG.md).

**Comment by Dids** [comment]
@steffenagger The declarations are indeed there, but calling them throws an exception at runtime, unless called through the constructor, see this previous comment here: https://github.com/realm/realm-js/issues/2903#issuecomment-635940381

**Comment by mattmogford** [comment]
I see it at the top of the CHANGELOG, but with no version number.
Is this released yet on a version?

**Comment by steffenagger** [comment]
@Dids sorry for the late reply. Is Foo an interface (with separate schema) or a class model?

Class models does _not_ automatically get extended with `Realm.Object`, even though the current TS declaration states it. The correct way for class models would be to extend `Realm.Object` - but before I waste your time with that approach, then i should inform you that `Realm.Object` is not currently extendable in TS, due to the declarations..
There's currently a PR draft that solves those issues here: https://github.com/realm/realm-js/pull/3013

We are focusing on getting v10 out of beta, so I'm fairly sure these changes will land in v10 beta first (https://github.com/realm/realm-js/pull/3044)

@mattmogford No, the missing version number indicates it hasn't yet been release. The upcoming v6 release is still awaiting some changes.
