### ISSUE TITLE
Not possible to create Realm.Credentials.jwt(token) with "realm": "v10.0.0-beta.9"

### ISSUE THREAD

**Issue by janfi** [realm/realm-js#3073]
Hello,

I'd like to create Realm.Credentials from jwt with the SDK "realm": "v10.0.0-beta.9"  but it seems it's not available.

I'd like to do the same thing I did with "realm-web"
```javascript
const credentials = Realm.Credentials.jwt(token);
```
Could you confirm that ?

thanks,

**Comment by janfi** [comment]
"realm": "v10.0.0-beta.9"

```javascript
const credentials = Realm.Credentials.custom(token);
````
not available either in react-native SDK.

thanks

**Comment by janfi** [comment]
Hello,

It's just a typescript issue.

Add 
```javascript
static custom(token: string): Credentials<Credentials.JWTPayload>;
```
in the file app.d.ts in the node_modules package 'realm', folder '/types'.

**Comment by kraenhansen** [comment]
Thanks for reporting this.
We need to rename `custom` to `jwt` in Realm JS, since [Realm Java](https://docs.mongodb.com/realm-sdks/android/10.0.0-beta.4/javadoc/io/realm/mongodb/Credentials.html#jwt-java.lang.String-), [Realm Swift / ObjC](https://docs.mongodb.com/realm-sdks/objc/10.0.0-beta.2/Classes/RLMAppCredentials.html#/c:objc(cs)RLMAppCredentials(cm)credentialsWithJWT:) and [Realm Web](https://github.com/realm/realm-js/blob/v10/packages/realm-web/src/Credentials.ts#L112-L122) have all chosen that name.
