### ISSUE TITLE
realm class error when having property with string[], RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by enigmablue** [realm/realm-js#3139]
Background: I'm using realm 3.6. I've been trying to migrate to the latest realm for ages but can't seem to get it to work out of the box. On 3.6 i'm using classes + static methods so i can just do stuff like Person.getById() and stuff. So i'm trying to do the same.

For this example, I'm trying to do a simple string[] property on a realm class on a completely new react native init().

```
class Person {
  get fullName() {
    return this.firstName + ' ' + this.lastName;
  }
  get homes(){
    return this.homes
  }
}
Person.schema = {
  name: 'Person',
  properties: {
    firstName: 'string',
    lastName: 'string',
    homes: 'string[]',
  }
}; 
```

This is my write and call method

```
  realm.write(() => {
            const john = realm.create('Person', {
              firstName: 'John',
              lastName: 'Smith',
              homes: ['singapore', 'indonesia']
              });
              });
              let persons = realm.objects('Person');

              for (let p of persons){
                console.log("p full name", p.fullName)
                console.log("p homes", p.homes)
                }
              });
              }, [])
```

The p full name gets called but the homes hit an error.
How do i make a string array on a class property here?

```
2020-08-15 10:03:24.083678+0800 realmlatest[72453:3711753] [javascript] 'p full name', 'John Smith'
2020-08-15 10:03:24.200279+0800 realmlatest[72453:3711753] [javascript] Possible Unhandled Promise Rejection (id: 3):
RangeError: Maximum call stack size exceeded.
```

**Comment by kraenhansen** [comment]
You're experiencing "Maximum call stack size exceeded." because the `homes` getter implementation is calling itself recursively. When reading an object from the data base (as you do with your call to `realm.objects('Person')`, you'll get a collection of objects that have the properties defined by the schema patched in via the objects `prototype`.

This is why you don't need to declare `firstName`, `lastName` or `homes` as getters on the `Person`.

Try removing the `get homes() {` and reopen the issue (or another) if the issue persists.
