### ISSUE TITLE
"Error: Invalid predicate" on special character in filter query

### ISSUE THREAD

**Issue by mahipalsingh-syt** [realm/realm-js#3193]
RealmDb thrown exception  **"Error: Invalid predicate"** when i added special character **double quote "** and **Back Slash**\ in filter query to get result.

Here i attached Screenshot from Realm Studio and same error i received on code base.

<img width="792" alt="Screenshot 2020-09-04 at 4 56 00 PM" src="https://user-images.githubusercontent.com/64964760/92235093-c8effa00-eed0-11ea-916a-b695e41e56ee.png">

<img width="782" alt="Screenshot 2020-09-04 at 4 56 43 PM" src="https://user-images.githubusercontent.com/64964760/92235109-cdb4ae00-eed0-11ea-9e0e-997d52599e25.png">

**Invalid predicate** is showing because i'm using special characters **double quote "** and **Back Slash**\  in field name and those characters are actually used in filter query URL.
  
could you please provide any suggestion or solution how can i get it resolve without removing any special characters from field name.

Plateform : React Native
"react": "16.11.0",
"react-native": "0.62.2",
"realm": "^6.1.0",

**Comment by kraenhansen** [comment]
Have you tried using placeholders for the values? (see https://realm.io/docs/javascript/6.0.0/api/Realm.Results.html#filtered)

```javascript
results.filtered('id = $0 && name = $1', 'e127345e-f0d7-11ea-adc1-0242ac120002', 'Banana \\season"')
```

The reason I'm using a double backslask `\\` in the string is because backslash is [an "escape character" when defining a string value in JavaScript code](https://www.w3schools.com/js/js_strings.asp).

**Comment by mahipalsingh-syt** [comment]
@kraenhansen  sorry still have same issue.
for temporary  i have fixed by applying filter on Array.

```
 let realmObject = this.realmInstance.objects("WORLD_SCHEMA").filtered("world_id=${id}")
let searchCountry = "IN"" // "IN\"
let filterArrayByName = realmObject.filter(country=>country.name == searchCountry)

```

**Comment by ironage** [comment]
The query syntax with variable substitution suggested by @kraenhansen should work. Note the difference between the Realm variable substitution using `$0` (this should work) and javascript variable substitution `${id}` which is the same as feeding the raw string into the query engine (which won't work with special characters).

@mahipalsingh-syt can you share the exact syntax of the query that isn't working for you? I've tested special characters in a variable substitution query and it's working for me so in order to help you further I'll have to take a look at exactly what you're doing.

**Comment by fronck** [comment]
@mahipalsingh-syt Have you been able to try the suggestions above? And if so, were you able to fix your issue?
