### ISSUE TITLE
Relationships not working anymore? What is $refId ?

### ISSUE THREAD

**Issue by Hurdock** [realm/realm-js#3234]
Hey guys. I just moved to the latest version.

My code looks like this:

```
let rowsFetched = realm.objects('Bookings').filtered(`state == "idle"`).sorted('datetime', false);
rowsFetched = JSON.parse(JSON.stringify(rowsFetched, Realm.JsonSerializationReplacer))
```

Questions:

Why exactly is my result now looking like this ? 

My issue: 

The parent object should had the parent properties. I have a relationship set from booking to the parent object schema. But now it has a "ref" so how should I fix this ?
```
{
        "$refId": "{0000-004d}",
        "booking_id": "71fc09a7-907d-433a-b925-f833c1ee36a7",
        "parent": {
            "$ref": "{0000-004d}"
        }
}
```
What is that $ref ? And why is changed ? Because in the previous version that I was using, the "parent" property object was having was the parentObject properties inside. Are the relationships no longer working, do I have now to fetch the parent manually ? If I fetch the booking, is it no longer gonna fetch the relationships inside down the line ?

The schema looks like this:

```


export const bookings = {
  name: 'Bookings',
  properties: {
    booking_id: 'string',
    parent: 'BookingParent',
  }
}

export const BookingParentSchema = {
  name: 'BookingParent',
  properties: {
    state: 'string',
    contract: 'string',
  }
}

```

**Comment by Hurdock** [comment]
Something is very wrong!!!

```
 {
        "$refId": "{0000-004d}",
        "booking_id": "71fc09a7-907d-433a-b925-f833c1ee36a7",
        "parent": {
            "$ref": "{0000-004d}"
        },
        "assignee": "valentin@gogogog.com",
        "datetime": "2020-09-18T10:05:39+01:00",
        "voucher": "TRAININGJOB",
        "targets": [
            {
                "$refId": "{0000-00a0}",
                "type": "email",
                "value": "test@test.com"
            },
            {
                "$refId": "{0000-00a1}",
                "type": "phone",
                "value": "+4554545445"
            }
        ],
        "location": {
            "$ref": "{0000-004d}"
        },
        "address": {
            "$ref": "{0000-004d}"
        },
        "contacts": [
            {
                "$refId": "{0000-009a}",
                "target_id": "fbf2b5c5-4f25-4c6b-845f-66e798465e40",
                // THIS IS THE PROPERTY SCHEMA ACTUALLY

```

The targets property data and contacts have ben swapped! As you can see inside the contacts array, we have target data, and inside the targets we have contacts data ?!?!

**Comment by Hurdock** [comment]
Update: I can confirm, I've checked the data inside the database using Mongo Realm studio and the database is fine, the way Realm JS Is fetching the data is the one with issues!

**Comment by steffenagger** [comment]
@Hurdock `Realm.JsonSerializationReplacer` is a replacer for serialization with circular structures (as these are impossible to represent in a string), and is not meant to be directly parsable.
This is why you see the added `$refId` & `{ $ref }`.

I assume you are doing this to get plain JS objects, instead of `Realm.Object` etc:
```js
let rowsFetched = realm.objects('Bookings').filtered(`state == "idle"`).sorted('datetime', false);
rowsFetched = JSON.parse(JSON.stringify(rowsFetched, Realm.JsonSerializationReplacer))
```

Instead og serializing and then deserializing (`JSON.stringify`/`JSON.parse`), try calling `toJSON` directly on the `Realm.Object` or `Realm.Collection`, like so:
```js
const bookings = realm.objects('Bookings').filtered(`state == "idle"`).sorted('datetime', false);
const detached = bookings.toJSON();
```

More about [toJSON on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON_behavior)

**Comment by Hurdock** [comment]
```
const bookings = realm.objects('Bookings').filtered(`state == "idle"`).sorted('datetime', false);
const detached = bookings.toJSON();

``` 

Ok this look like a good example, but I got questions:

1. If I do it like this, am I going to get $refId still instead of my actual data like it used to ?
2. I may be wrong, but I remember yesterday doing it like that, but when I've tried console.log(JSON.stringify(bookings.toJSON(), null, 4)) to get a better view at the data, it was saying json stringify cannot be used on a object with circular references.

**Comment by steffenagger** [comment]
@Hurdock 

1. No, `$refId`/`{ $ref: 'id-string' }` is only added/replaced by `Realm.JsonSerializationReplacer`, and only to the stringified output (it will _not_ alter the data in Realm) - It will do this to avoid the problem you mention in question 2.
2. A circular structure is when an object contains "something" which references itself.
Example: `obj1` has a property pointing to a different object: `obj1.child --> obj2`. If `obj2` has a reference back to `obj1` (`obj2.parent --> obj1`), then you have a circular reference.
Trying to write this to a string is impossible, as the two objects will reference each other back and forth for eternity. This is where `Realm.JsonSerializationReplacer` can be used. When it detects it has seen an object before, it adds `{ $ref: 'primaryKey if the schema defines one, OR an internal temporary id string' }` instead of continuing the circular structure.
If you are working with larger nested structures, and/or circular structures (in this case), and would personally recommend attaching a debugger instead of using `console.log`.

I'm closing this issue, in hope that this answered your questions (otherwise let me know).
