### ISSUE TITLE
Error exchanging access code with OAuth2 provider (Google login, web SDK)

### ISSUE THREAD

**Issue by vegar** [realm/realm-js#3249]
This is most likely the same issue as #3116 but for the web sdk and not the nodejs sdk. 

## Goals

Authenticate using existing google account, as described in [the documentation](https://docs.mongodb.com/realm/web/authenticate/#google-oauth).

## Expected Results

Expect `app.logIn(Realm.Credentials.google(token))` to return a `Realm.User`

## Actual Results

Receives error instead:

```
Error: Request failed (POST https://eu-west-1.aws.stitch.mongodb.com/api/client/v2.0/app/math-grade-web-ktfrh/auth/providers/oauth2-google/login): error exchanging access code with OAuth2 provider (status 401)
    at DefaultNetworkTransport.fetchAndParse (bundle.dom.es.js:514)
    at async performLogIn (bundle.dom.es.js:1160)
    at async App.performLogIn (bundle.dom.es.js:2385)
    at async App.logIn (bundle.dom.es.js:2295)
    at async loginAnonymous (RealmContext.tsx:32)
```

## Steps to Reproduce

* Get hold of google auth-token
* Pass google auth-token to Realm.App login method

## Code Sample

```
import * as Realm from "realm-web";
import { useGoogleLogin } from 'react-use-googlelogin';
import { GoogleUser } from 'react-use-googlelogin/dist/types';

const app: Realm.App = new Realm.App({ id: process.env.REACT_APP_REALM_APP_ID });
const googleAuth = useGoogleLogin({
        clientId:  process.env.REACT_APP_GOOGLE_CLIENT,
        cookiePolicy: "none"
    });

try {
    const googleUser = await googleAuth.signIn() as GoogleUser;    
    const user: Realm.User = await app.logIn(Realm.Credentials.google(googleUser.tokenId));
} catch (error) {
    console.log(error)
}

```

## Version of Realm and Tooling

- Realm JS SDK Version: realm-web@0.8.1
- Node or React Native: Browser
- Client OS & Version: Windows 10
- Which debugger for React Native: ?/None

**Comment by campfiretechnology** [comment]
Having what I think is the same issue here with the web SDK. The error message I get is:

```
bundle.dom.es.js:2718 Uncaught (in promise) Error: Request failed (POST https://stitch.mongodb.com/api/client/v2.0/app/blaze-backend-oerzm/auth/providers/oauth2-google/login?device=[token redacted]): error exchanging access code with OAuth2 provider (status 401)
    at Function.fromRequestAndResponse (bundle.dom.es.js:2747)
    at async Fetcher.fetch (bundle.dom.es.js:2905)
    at async Fetcher.fetchJSON (bundle.dom.es.js:2922)
    at async Authenticator.authenticate (bundle.dom.es.js:2646)
    at async App.logIn (bundle.dom.es.js:3095)
```

**Comment by mburdette** [comment]
@vegar try using the auth code from the google response and not the `tokenId` for the credential.

**Comment by vegar** [comment]
The [`GoogleAuth.signIn`](https://developers.google.com/identity/sign-in/web/reference#googleauthsigninoptions) call returns me a `googleUser` with an `accessToken` on the form `ya29.*` and a `tokenId`on the form `eyJh*`. It returns nothing else that looks like a token.

I can instead use the [`GoogleAuth.grantOfflineAccess()`](https://developers.google.com/identity/sign-in/web/reference#googleauthgrantofflineaccessoptions) method which returns a token in the form of `4/4wG*`.

It doesn't matter which one I pass along to MongoDb Realm. I'm always rewarded with the same error.

I've also tried with realm-web@0.9.0.

**Comment by kraenhansen** [comment]
A couple of updates:
- If you're using the "react-use-googlelogin" package, you should definitely use the `grantOfflineAccess()` since that will allow you to retrieve the "auth code". This is a "one time" secret, which means if the browser uses that to complete the auth flow (as it does when calling signIn to exchange the auth code for Google access and refresh tokens), the MongoDB Realm server won't be able to use the code too.
- We're currently experiencing an issue with a breaking change in the service API that we've been using to exchange the auth code to access and refresh tokens, which is what you see as an "error exchanging access code with OAuth2 provider" - this is an issue across all our SDKs and I'll make sure to update this issue when the underlying issue gets resolved.

For now, my best suggestion forward would be for you to use the "redirect url" variant of the Google credentials:
- Follow [the guide to configure the Google authentication provider](https://docs.mongodb.com/realm/authentication/google/), paying extra careful attention to setting up the redirect uris.
- Call the `logIn` method with google credentials passing in a URI instead of the auth code:
    ```javascript
    const credentials = Credentials.google("http://localhost:8080/google-callback");
    const user = await app.logIn(credentials);
    ```
- Once the user gets redirected to your app (on "http://localhost:8080/google-callback" in this example), call the `handleAuthRedirect` function to read out the auth code from the URL and store it to complete the flow:
    ```javascript
    import { handleAuthRedirect } from "realm-web";
    handleAuthRedirect();
    ```

I'm truly sorry for the inconvenience here and I want you to know we're working hard on resolving the underlying issue between the server and the Google service, and I hope alternative way of authenticating would work sufficiently (at least until we get a fix on the other issue).

**Comment by vegar** [comment]
Alright. Good to know I'm not doing something wrong. ;-)

**Comment by kraenhansen** [comment]
Just circling back here: We're still working on a solution to the underlying issue and unfortunately I can't provide an ETA yet.

**Comment by afreakk** [comment]
Hi, still having the same issue, any ETA now?

**Comment by kraenhansen** [comment]
@afreakk I'm sorry that I didn't update this issue when the release came out.
[Realm Web v1.1.0](https://github.com/realm/realm-js/releases/tag/realm-web-v1.1.0) was released with a fix for this via https://github.com/realm/realm-js/pull/3440.

**Comment by idanstark42** [comment]
Hello,
I'm using realm-web v1.5.1, yet I'm still facing this issue.
I'm not using `react-use-googlelogin`, instead using the new Google Identity.
I am getting from it the JWT with the credentials encoded, but when I pass it into `app.logIn` function it throws an error.
Do you know what I'm doing wrong?

Thank you
Idan
