### ISSUE TITLE
"Must first create RPC session with a valid host" while debugging in React Native

### ISSUE THREAD

**Issue by uripre** [realm/realm-js#3399]
Referring back to this closed issue: https://github.com/realm/realm-js/issues/885

The issue was closed because it "was discussed" but no reference given to the discussion, and numerous people still encounter it.

Could you please comment? I really like Realm so far but clearly cannot just live without the ability to debug my application.

**Comment by fronck** [comment]
Hi @uripre.  Thanks for your interest in Realm.

We are working on improving React Native debugging, and it should land in one of the next few releases.

**Comment by uripre** [comment]
Thank you @fronck for getting back to us! Just two clarifications if possible:

1. Is it true that currently you cannot debug react native applications when using Realm? Is there a workaround you can refer me to?
2. Sorry to push you on this, but I'm unfamiliar with the release schedule you guys have, are we talking about weeks, months...?

**Comment by fronck** [comment]
No problem, @uripre.

1. If you're debugging on MacOS+iOS, you may have luck using Safari (see [this comment](https://github.com/realm/realm-js/issues/3358#issuecomment-721580904)).
2. We do have a fairly rapid release schedule, releasing whenever high-priority features are ready rather than on a fixed cadence.  This issue is a highly-requested fix, and as such high priority.  So, we aren't talking about months.

**Comment by uripre** [comment]
Thanks @fronck. Going to close this ticket, and follow the one you linked to: https://github.com/realm/realm-js/issues/3358

Really looking forward for a fix for this one.
