### ISSUE TITLE
Retrieved data from realm is empty in React Native on android

### ISSUE THREAD

**Issue by zfanta** [realm/realm-js#3427]
## Goals

Retrieve data from realm.

## Expected Results

A Realm object from `realm.create`, `realm.objects` should not be empty.

## Actual Results

Retrieved data is empty.
![image](https://user-images.githubusercontent.com/6619332/100252762-97dd0e00-2f83-11eb-9086-d09b961ada1e.png)

But writing operation works.
![image](https://user-images.githubusercontent.com/6619332/100252827-adeace80-2f83-11eb-8a03-3a483c88f3b0.png)

## Steps to Reproduce

`yarn react-native run-android`

## Code Sample

https://github.com/zfanta/AwesomeTSProject on commit `7d2ca064ea90a233ceea92f518c0b325802f62d1`

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.1
- Node or React Native: 0.63.3
- Client OS & Version: Windows 10 Pro 2004 (build 19041.630)
- Which debugger for React Native: None
- Android API: 29
- Android CPU/ABI: x86

**Comment by cesarvr** [comment]
I think the problem here is that `console.log` cannot introspect the ``Realm.model`` returned by the ``Realm.create``. This happens because ``Realm.model`` doesn't implement ``toString()`` and won't provide more details. 

For more information you can look at [this issue.](https://github.com/realm/realm-js/issues/3306#issuecomment-705393341)
