### ISSUE TITLE
Support accessing/querying backlinks

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#343]
We will probably want to support virtual properties the same as cocoa.

**Comment by joshuapinter** [comment]
Any timeline on this, Alazier? Would be great to have in there. Thanks!

**Comment by joshuapinter** [comment]
@alazier Also, I'm storing the `parentId` as a property of a child object and then manually looking up the `parent` object from that `parentId` value. 

Is there a better way to do this? I've seen some existence of linking in other documentation, like [Swift](https://realm.io/docs/swift/latest/#inverse-relationships), but not sure if Realm JS supports this. Can you shed some light on this and maybe a best practice that we can use in the meantime.

Thanks!

**Comment by alazier** [comment]
Linking works on the other bindings but we haven't added the feature to JS
yet as we would like to do it right. Don't have a timeline but we can bump
up the priority. Most of the underlying functionality is built and just
needs to be exposed so hopefully this won't take too long to build.

**Comment by astigsen** [comment]
>  I'm storing the parentId as a property of a child object and then manually looking up the parent object from that parentId value.

While implicit backlinks are not supported yet, you can still do direct linking with object properties. That will at least remove the need for parentId's and manual lookups:
https://realm.io/docs/react-native/latest/#object-properties

**Comment by joshuapinter** [comment]
@astigsen Right, so instead of using `parentId` I could just use `parent` and then link to the `Parent` object? I imagine this doesn't work when creating a `Parent` record along with the nested `Children` record all in one write, like so: 

```js
realm.write(() => {
  realm.create('Person', {
    name: 'Joe',
    car: {make: 'Honda', model: 'Accord', drive: 'awd', person: ...},
  });
});
```

You would have to create the `Person` object first and then link to it, like this: 

```js
realm.write(() => {
  let person = realm.create('Person', {
    name: 'Joe',
    car: {make: 'Honda', model: 'Accord', drive: 'awd'}
  });

  person.car.person = person;
});
```

Does that look right?

**Comment by appden** [comment]
@joshuapinter That looks right to me.

**Comment by joshuapinter** [comment]
Thanks @appden! Would be good to throw this in the docs as well.

**Comment by martigasco** [comment]
@astigsen I'm thinking your suggested solution would take a heavy penalty at creation time, especially in mass insertion scenarios (like syncing with a remote API), wouldn't it?

The fastest way I can think of inserting a big tree of data is precisely inserting a parsed JSON tree into the parent model, which has "list" references to its children, and many levels down the same way. This would be one create operation, whereas having to retain reference to each object which has children and then passing the reference to each child can become a nightmare, I'm guessing not only coding but also in performance, given that you need to call "write" in order to get the reference to the parent object.

Does this make any sense? I'm quite new to non-relational dbs, so forgive me if I said something nonsense.

Also, are there any close plans of implementing the backlinks any other way?

**Comment by kristiandupont** [comment]
@martigasco did you see the example above? I agree that it's suboptimal but I wouldn't quite call it a nightmare. There is some added performance overhead but it *is* just a matter of setting a reference so I doubt it will be too costly.
We will implement proper backlinks as the other SDK's have, there are just a number of other things that have priority as well so we can't quite say when that will be.

**Comment by astigsen** [comment]
> you need to call "write" in order to get the reference to the parent object.

There is no need to call `write` just to get the reference. You can obtain that outside the write transaction. You only need that when modifying data.

**Comment by martigasco** [comment]
@kristiandupont I agree it's just some added performance overhead in most "lightweight" cases, but I'm facing an scenario where the data insertion i'm performing is taking 21 seconds so far, without setting this backlink references (only the "children" list-kind), so I'm thinking it could only increase this long time, considering we're talking about a mobile platform 😅

@astigsen I understand, but in this particular case of mine, where I'm performing a batch insert with an empty Realm, I can't think of any other way apart from doing the (forgive me, it was create, not write). But still, I need to get the reference inside the transaction, as the parent object to be referenced is being inserted as well (I hope I explained this in a clear way, I am well aware it's quite a heavy example):
```
{"companies":
  [
  {
    "id": 1,
    "employees": [
      {"id":1, "name":"John", "phone": "12345"},
      {"id":2, "name":"John", "phone": "12345"},
      {"id":3, "name":"John", "phone": "12345"},
      {"id":4, "name":"John", "phone": "12345"},
    ]
  },
  {
    "id": 1,
    "employees": [
      {"id":1, "name":"John", "phone": "12345"},
      {"id":2, "name":"John", "phone": "12345"},
      {"id":3, "name":"John", "phone": "12345"},
      {"id":4, "name":"John", "phone": "12345"},
    ]
  }
]}
```

In this example, we could say i'm inserting the "companies" object in just one operation, with all of its 5 or 6 level deep children. What we're talking here is managing to make a reference to its parent from every level of the tree, but if I perform a single nested insert, I don't have (yet) a reference to any parent when inserting a given child.

**Comment by martigasco** [comment]
I just tried to apply this procedure to the first two levels of children in my tree (the top level model has 6 items, the second level 34, and the third 466). Just by doing a 3-level nested loop through each one of these in order to assign a reference to the parent (from the upper iteration), the insert time went from 21 seconds to more than 12 minutes (I say more than 12 because I stopped it before finishing and letting my laptop literally melt lol).

Maybe I'm doing something wrong, but if that's not the case it's a real pity... I was really looking forward to improving my current insert times with Core Data (2 min), which should be beatable considering it carries a lot of stuff on top of Sqlite :(

**Comment by bdash** [comment]
@martigasco, in my opinion it would be best to file a new issue that includes more detail about what you're doing, including the relevant portion of the code you're using. That will avoid muddying up this issue which is tracking exposing Realm's backlinks in the JS SDK. It's likely that we can help you improve your approach if we can see the code you're using.

**Comment by martigasco** [comment]
@bdash Just did it, thanks! #767

**Comment by Zhuinden** [comment]
@kristiandupont I am trying to do linking objects link query using query language [like so](https://stackoverflow.com/questions/47330267/how-to-do-subquery-in-realm-react-native/47333427?noredirect=1#comment81619452_47333427):

```
let queryFilter = 'combinations.onSale = "yes" AND productId = 1';
```

It says `Property 'onSale' is not a link in object of type 'Combination'`

How do you do a link query with the Realm-JS query api?

**Comment by bdash** [comment]
@Zhuinden, queries involving backlinks are not yet supported by Realm JS.

**Comment by Zhuinden** [comment]
@bdash is that tracked anywhere? I couldn't find it which is why I asked in this thread.

**Comment by bdash** [comment]
I'm not sure. Feel free to file an enhancement request, and someone on the Realm JS team can tag it as a duplicate if they happen to find it is already tracked.

**Comment by Zhuinden** [comment]
I've opened https://github.com/realm/realm-js/issues/1498 thanks
