### ISSUE TITLE
iOS App Crash after React Native Reload and Login

### ISSUE THREAD

**Issue by matt2legit** [realm/realm-js#3457]
## Goals

Reload the app during development and be able to login again.

## Actual Results

App crashes with the following error and stack trace:
`com.facebook.react.JavaScript (26): EXC_BAD_ACCESS (code=1, address=0x40000000010d7ed8)`

![Screen Shot 2020-12-09 at 1 02 55 PM](https://user-images.githubusercontent.com/18034024/101668782-fcd24280-3a1e-11eb-8fd3-577bd11db38f.png)

## Steps to Reproduce

1. Build App on iOS Device
2. Login via Realm
3. Shake Device to Reload
4. Attempt to login with Realm again
5. App Crashes

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.1
- React Native: 0.63.4
- Client OS & Version: iOS - Xcode 12.2

**Comment by kneth** [comment]
@matt2legit Thank you for reporting. 

I believe the issue is the the first network transport isn't removed, and it will try to use the old JavaScript main thread (which has been removed). We have work-in-progress for other issues with the Chrome debugger (see https://github.com/realm/realm-js/pull/3456), and we will include this in that work.
