### ISSUE TITLE
Return "{}" instead of undefined/null

### ISSUE THREAD

**Issue by jjalonso** [realm/realm-js#3484]
Im not sure if this is a bug or a feature, but i have a document with this structure

```
{
_id: 5fdcd2857ee3281e8567ec87
user_id: "5fdcd2857ee3281e8567ec40"
publicName:"cuenta invoice"
}
```

## Goals

Im trying to get photo attribute via
```
export const GET_STORE_SETTING = gql`
query ($userId: String!) {
  store (query: {owner_id: $userId} ) {
    name
  }
  profile (query: {user_id: $userId}) {
    publicName
    photo <--------------
  }
}
`;
```

## Expected Results

Because photo doesnt exist in document yet, i expect to get a payload where photo is null or undefined

## Actual Results

The photo value that i get in the payload is "{}"

```
profile: {__typename: "Profile", photo: "{}", publicName: "cuenta invoice"}
    photo: "{}"  <---------------------
    publicName: "cuenta invoice"
    __typename: "Profile"
store: {__typename: "Store", name: "Tienda 1"}
    name: "Tienda 1"
    __typename: "Store"


```

## Version of Realm and Tooling

- Realm JS SDK Version: 1.1.0
- Node or React Native: js browser
- Client OS & Version: Chrome mac
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
@jjalonso Thank you for reporting. I believe it is a bug.

**Comment by jjalonso** [comment]
I think so. Keep the ticket updated please.

**Comment by kraenhansen** [comment]
It looks like you're issuing a GraphQL query.

Since GraphQL is not explicitly supported by Realm JS / Realm Web (only used for authentication), I think it would be better to create a post on https://community.mongodb.com/

If you leave this issue as is, I'll try to create the appropriate issue elsewhere when I get back from the holidays.

**Comment by jjalonso** [comment]
what you mean that its not supported? its supported not by realm-js lib
maybe but it is from realm platform, and i guess is the realm platform
graphql server the one that fail returning {} isnt?

In order to create it in the proper place, unfortunately  yes, please,
could you posted internally where you think it belong to and if is public
please reference it here. thanks.

**Comment by sumedham** [comment]
Hey @jjalonso  - I do believe we already return `null` when a property in a schema is not defined yet. Here is an example I tried:

Query:
![image](https://user-images.githubusercontent.com/7637511/103290226-a8333f00-49ae-11eb-926e-ba25bdf86047.png)
Result:
![image](https://user-images.githubusercontent.com/7637511/103290244-b2553d80-49ae-11eb-911b-4ccf07f9b07f.png)
Document In Question:
![image](https://user-images.githubusercontent.com/7637511/103290280-c731d100-49ae-11eb-8a00-7fb1f86fce86.png)


Is it possible that your schema has defined `photo` as different type and do you mind pasting the full document that you are trying to query from Atlas? Also what GraphQL client are you using alongside the JS SDK?

Since this is a Realm GraphQL API question, please post the original question and responses [ in the MongoDB Realm forum
](https://developer.mongodb.com/community/forums/c/realm/9/)? The github issues here are meant for JS SDK specific issues.

**Comment by kraenhansen** [comment]
@jjalonso did you make any progress on this?

**Comment by jjalonso** [comment]
Hi guys, im sorry but i could not give more data about it since we leaving
realm for our MVP and we not working with that codebase anymore. thanks
anyway and hope it works for the future is somebody find same issue.
