### ISSUE TITLE
Improve error message when inserting a list into a mixed property

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#3730]
## Goals

Clear and actionable error messages.

## Expected Results

An error message such as:

> A mixed property doesn't support lists of values

## Actual Results

The following error is thrown:

> Error: Only Realm instances are supported.

## Steps to Reproduce & Code Sample

1. Open a Realm with a schema declaring a mixed property.
2. Try inserting a list of values

```typescript
const realm = new Realm({
  schema: [{
    name: "MixedClass",
    properties: { value: "mixed" },
  }],
});
realm.write(() => {
  realm.create("MixedClass", { value: [123, false, "hello"] });
});
```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.5.0-beta.1
- Node or React Native: Tested on Node.js
- Client OS & Version: N/A
- Which debugger for React Native: None

**Comment by davidaharlow** [comment]
Same For Me with 10.5.0  (not beta)

Expected:
A mixed property doesn't support lists of values

Actual:
Error writing to realm: Error: Only Realm instances are supported.

Version of Realm and Tooling
Realm JS SDK Version: 10.5.0
Node or React Native: Tested on React Native
Which debugger for React Native: Flipper

**Comment by kneth** [comment]
The reason is that we have a late type deduction for Mixed values, and the code path followed in this case is that array is interpreted as an object (which is a link when it is stored in Realm) since `Array` is also an `Object` in JavaScript. 

We should put in an earlier check to guard against array and other not support types.
