### ISSUE TITLE
Unable to build on Catalyst

### ISSUE THREAD

**Issue by marcosrdz** [realm/realm-js#3750]
When attempting to build a Mac Catalyst app using RealmJS  10.4.1 I get this error:

d: warning: directory not found for option '-L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/iOSSupport/usr/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/maccatalyst'
ld: in /Users/marcos.rodriguez/Documents/GitHub/BlueWallet/node_modules/realm/react-native/ios/realm-js-ios.xcframework/ios-arm64_armv7/librealm-js-ios.a(platform.o), building for Mac Catalyst, but linking in object file built for iOS, file '/Users/marcos.rodriguez/Documents/GitHub/BlueWallet/node_modules/realm/react-native/ios/realm-js-ios.xcframework/ios-arm64_armv7/librealm-js-ios.a'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kneth** [comment]
We currently don't have support for Catalyst but I believe we can add it relatively easy.

Mostly an internal note (or partial todo list):

* [ ] Use the `maccatalyst.toolchain.cmake` instead of `ios.toolchain.cmake` in https://github.com/realm/realm-js/blob/master/scripts/build-ios.sh#L39
* [ ] Either expand `build-ios.sh` or create new tool to drive the build process
* [ ] Create `cmake/maccatalyst.toolchain.cmake` similar to `cmake/ios.toolchain.cmake`
* [ ] Include Catalyst in `RealmJS.podspec`

**Comment by marcosrdz** [comment]
Any updates?

**Comment by kneth** [comment]
We haven't had a breakthrough yet but we are working on it. It turns out that building for [Catalyst using CMake isn't trivial](https://gitlab.kitware.com/cmake/cmake/-/issues/20132).
