### ISSUE TITLE
Adding Arrays Object into Realm DB causing an issue ''Error: Error: Array must contain values for all object properties"

### ISSUE THREAD

**Issue by SanjanaTailor** [realm/realm-js#3756]
sing RealmDB following code is listed below

```
const object = [{id="1"}, {id="2"}, {id="3"}, {id="4"}];
const data = await RealmDB.add(Student_SCHEMAS.student_DATA, object);
Student Schema as shown below:

StudentData = {
    name = "student",
    primaryKey = "id",
    properties: {
         id:'int'
     },
};
```
Error: Array must contain values for all object properties and data are not inserted.

Object size is currently 15MB, so what is the way to add data in Realm with this type of objects.

Anything I need to change in schema.

Please suggest, thank you

**Comment by kraenhansen** [comment]
@SanjanaTailor I see you've cross posted this from https://stackoverflow.com/questions/67720196/adding-arrays-object-into-realm-db-causing-an-issue-error-error-array-must-c. Please share a link to the Stack Overflow post next time around.

You're mentioning `RealmDB.add`, which is not a part of the Realm JS API as I know it, are you using some kind of wrapper around the Realm JS API? You're also using equal signs `=` instead of colons `:` a couple of places. What dialect of JavaScript are you using here?

Here's an example of what I think your code would look like:

```javascript
const Realm = require("realm");

const studentSchema = {
  name: "Student",
  primaryKey: "id",
  properties: {
       id: "int"
   },
}

const objects = [{id: 1}, {id: 2}, {id: 3}, {id: 4}];

const realm = new Realm({ schema: [studentSchema] });
realm.write(() => {
  for (const object of objects) {
    realm.create("Student", object);
  }
});
```

Another great place to get help on using Realm JS is [our MongoDB Community forums](https://developer.mongodb.com/community/forums/c/realm-sdks/58).
