### ISSUE TITLE
Is anyone here using realm-js with React native in production?

### ISSUE THREAD

**Issue by ngort01** [realm/realm-js#3821]
And if you do, how are you dealing with debugging?
I would like to use it, but storing saveral hundred objetcs completly breaks debugging in Chrome and this is a huge blocker.
Debugging on Mac + Safari is not an option because not everyone is using a Mac.

Any ideas or workaraounds?

**Comment by tonygomez** [comment]
We are using it in production. We all have macs but its still annoying not being able to use chrome.  How are you dealing with having to create a schema for a schema-less database ¯\_(ツ)_/¯?  Feel like that should be optional.

**Comment by ngort01** [comment]
I don't have any problems with a creating schema, at least not in my usecase. Only the debugging problem leads me back to good old SQL Lite... :D Too bad, cause I think Realm is easier to setup and use.

**Comment by YaoHuiJi** [comment]
Debugging is the biggest pain to me for several years  until I find realm doesn't support Hermes, I don't think people will use realm-js in their new react-native projects because of this.

**Comment by leecommamichael** [comment]
I am using this library with React Native in production. Performance profiling is the biggest pain. There is a vicious cycle in my project wherein React can re-render, causing Realm to re-query, which causes React to re-render and so on...

The team at Mongo is enabling Hermes on iOS soon, and it will be glorious.

I'd be remiss not to share, I have (since starting using React Native) found Flutter to be a smoother app-development experience and Mongo is developing Realm for Flutter.

**Comment by tonygomez** [comment]
@leecommamichael what do you like more about flutter over rn development?

**Comment by leecommamichael** [comment]
> @leecommamichael what do you like more about flutter over rn development?

I come from a compiled-language background with a love for types. I write React Native with TypeScript. I don't like spending 10 minutes deciding the best way to `: type` something, and with TypeScript's expressiveness, I find myself and teammates doing that. The worst of it comes when you need to read a type-mismatch from TypeScript, I've seen some errors as long as 5 paragraphs. The Dart language (used with Flutter) is a simple, boring language. The debugging, profiling, and static analysis are great, and the compiler is fast.

This, and, I always hated designing the perfect layout in React Native and then discovering that it doesn't look good or work at all when run on the platform I wasn't testing on (Android vs iOS UI layout). Flutter renders identically regardless of platform. I enjoy the included testing library in `flutter_test`. It is every bit as intuitive as `jest`, and requires little-to-no configuration to work properly. Sometimes it can be a pain to get `jest` to play nicely with TypeScript and the slew of dependencies needed to build a React Native app.

Because I use Material Design, I find Flutter has everything I need built in. I don't have to think as a designer would, I get sensible defaults and a short list of dependencies. This pleases our designers as well, they tend to think in Material Design and are pleased when we can deliver on exactly what they wanted. It's just fun all around with Flutter.

As always with tech, your mileage may vary. Your values may not be the same as mine.

**Comment by kraenhansen** [comment]
@YaoHuiJi & @leecommamichael I just wanted update this ticket to ensure you're aware that we've shipped a couple of releases supporting Hermes on iOS and Android: See https://github.com/realm/realm-js/issues/3940 for our progress.

We see this as the future of debugging an app that depends on Realm JS and as such I'll close this issue.
