### ISSUE TITLE
[Help needed] Uploaded realm file to Google Drive is not readable by Realm Studio 

### ISSUE THREAD

**Issue by vizFlux** [realm/realm-js#3868]
## Goals
Uploading realm file to google drive as a backup

## Expected Results

- Uploaded realm file can be accessed later
- Uploaded realm file can be read by Realm Studio (this is how I verify if the uploaded realm file is working as expected)

## Actual Results
First of all, I did not start the Realm in react native with an encryption key.
While attempting to open the uploaded realm file via  Realm Studio, it prompts a dialog requesting 128-character hex-encoded encryption key.

## Code Sample
```ts
import RNFS from 'react-native-fs';
import Realm from 'realm';
import {
  GDrive,
  MimeTypes,
} from '@robinbobin/react-native-google-drive-api-wrapper';

const gdrive = new GDrive();
gdrive.accessToken = (await GoogleSignin.getTokens()).accessToken;

const fileToBackup = await RNFS.readFile(Realm.defaultPath, 'base64');

// create and upload new backup
if (!fileItem.exist) {
  backup = await gdrive.files
    .newMultipartUploader()
    .setData(fileToBackup, MimeTypes.BINARY)
    .setRequestBody({
      name: 'default.realm',
      mimeType: MimeTypes.BINARY,
      parents: [appFolder?.id],
    })
    .execute();

  return backup;
}
```

## Version of Realm and Tooling
- Realm JS SDK Version: 10.6.0
- Node or React Native: React Native
- Client OS & Version: Android 11
- Which debugger for React Native: Chrome Debugger

**Comment by kraenhansen** [comment]
@vizFlux the dialog asking for encryption key is displayed if opening the file fails, since we're not storing plaintext header, we can't know if the failure is because the file is encrypted or corrupted. Unfortunately in your case, I expect it to be the latter.

Please compare the contents of the file on disk before and after the upload/download cycle to verify nothing got corrupted in transit.
