### ISSUE TITLE
duplicate symbol libRealm and libRealmJS

### ISSUE THREAD

**Issue by charlesluo2014** [realm/realm-js#388]
hi,when i use realm-js in react-native ,and I also use Obj-C realm for the native code，it was throw link error，my xcode version is 7.x ；

duplicate symbol __ZNK5realm7Results9get_queryEv in:
    /Users/luolishu/Library/Developer/Xcode/DerivedData/ZowalkHR-csdfcsyulneiakdnuevndewqugzs/Build/Products/Debug-iphonesimulator/libRealm.a(results.o)
    /Users/luolishu/Library/Developer/Xcode/DerivedData/ZowalkHR-csdfcsyulneiakdnuevndewqugzs/Build/Products/Debug-iphonesimulator/libRealmJS.a(results.o)

how to solve this problem？

**Comment by alazier** [comment]
If you use the dynamic framework for Obj-C you may be able to avoid this issue.

**Comment by alazier** [comment]
Any luck with this?

**Comment by stevenp** [comment]
I encountered the same issue, and don't have the ability to use the dynamic framework because some of the Pod dependencies I'm using won't work as a framework, and it appears to be an all-or-nothing proposition. Any other suggestions?

**Comment by appden** [comment]
@stevenp As long as you don't need to support iOS 7, you should be able to use the Realm Cocoa dynamic framework while continuing to use your other Pod dependencies as static libraries. For that to work, you'll need to instead follow the [installation instructions](https://realm.io/docs/objc/latest/#installation) under the **Dynamic Framework** section, rather than using CocoaPods to install Realm.

**Comment by stevenp** [comment]
@appden Thanks for the tip! I'll install that way instead.
