### ISSUE TITLE
Move to electron-fetch based on electron's 'net' module

### ISSUE THREAD

**Issue by untoldbyte** [realm/realm-js#4033]
### Problem

The current realm js code for node is suggested to be used in the electron platform as well

The code is using node-fetch and since its based on node's http module it needs to be provided proxy values. In that case the realmdb will hit a big limitation as mentioned here https://docs.mongodb.com/realm-sdks/js/latest/tutorial-http-proxy.html

I am a developer of an application that must run behind HTTP and HTTPS proxies
I am considering to move from POC to production with RealmDB but this limitation leaves the option unviable

### Solution

The current realm js code for node is suggested to be used in the electron platform as well

Since electron has both node and chromium using the 'net' module should allow automatic proxy negotiation and solve a big limitation as mentioned here https://docs.mongodb.com/realm-sdks/js/latest/tutorial-http-proxy.html

### How important is this improvement for you?

Dealbreaker

**Comment by kraenhansen** [comment]
Following the link you've shared, have you tried installing `electron-fetch` as `node-fetch`?

```sh
npm install node-fetch@npm:electron-fetch --prefix node_modules/realm-network-transport
```

**Comment by rahul-dutt-sharma** [comment]
This did not work, I get errors similar to Connection[1]: Connection closed due to error
Connected to endpoint '15.207.151.40:443' (from '192.168.68.105:57032')
ERROR: Websocket: Expected HTTP response 101 Switching Protocols, but received:
HTTP/1.1 401 Unauthorized
cache-control: no-cache, no-store, must-revalidate
connection: close
content-length: 212
content-type: application/json
date: Tue, 12 Apr 2022 02:24:10 GMT
server: envoy
vary: Origin
x-envoy-max-retries: 0
x-frame-options: DENY
