### ISSUE TITLE
The TsExample shows realm constructor must not return another value during debug with chrome

### ISSUE THREAD

**Issue by lamhtf** [realm/realm-js#4225]
I download the git template by
npx react-native init TsExample --template react-native-template-realm-ts

The package json with "react-native": "0.66.4", (suppose this to be a latest version of realm ts template)

After started the app i enabled the debug with chrome option.
I did not modify any code.

I can start the app normally
<img width="421" alt="Screenshot 2022-01-15 at 3 10 02 PM" src="https://user-images.githubusercontent.com/70745239/149613300-4d7631ca-64d5-41a6-961c-70a5b54141e9.png">

But after i tried to add any task description, the screen shows this error
**realm constructor must not return another value**
<img width="415" alt="Screenshot 2022-01-15 at 3 10 34 PM" src="https://user-images.githubusercontent.com/70745239/149613305-10363338-138a-4283-bfb0-ec66a3b40e5c.png">

**Comment by takameyer** [comment]
Hello @lamhtf :) Unfortunately, Realm does not work with the Chrome debugger, since we have to extend the native JS Engine.  We had a workaround, but it is very unstable and we are currently [removing all support for it](https://github.com/realm/realm-js/pull/4203). 

Realm does work well with the [safari debugger](https://reactnative.dev/docs/debugging#safari-developer-tools) and [flipper](https://fbflipper.com/).
