### ISSUE TITLE
 Realm has no setter or ivar for its bridge, which is not permitted, when debugging react native ios app

### ISSUE THREAD

**Issue by manarfalah** [realm/realm-js#4258]
### How frequently does the bug occur?

All the time

### Description

 when debugging react native ios app, getting crash on realm
![File](https://user-images.githubusercontent.com/6088761/150932329-6783b3d1-0027-487b-b7b0-46cba57395e3.jpg)
 

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

start IOS react native app
turn on debug mode

### Version

10.20.0-beta.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS

### Build environment

Which debugger for React Native: ..
react native 66.4

### Cocoapods version

1.11.2

**Comment by kraenhansen** [comment]
@manarfalah thanks for reaching out. Please note that the `10.20.x` releases of Realm JS is primarily intended for use with the Hermes engine and we advice [debugging using Flipper](https://fbflipper.com/docs/features/react-native/) instead of the legacy remote Chrome debugger

We'll soon publish a new `10.20.0-beta.1` which officially removes the code supporting the legacy Chrome debugger and should [provide a better error message](https://github.com/realm/realm-js/pull/4203).

As such, I'll close this issue.
