### ISSUE TITLE
Email/Password Authentication with dynamic Partition, 

### ISSUE THREAD

**Issue by reanzi** [realm/realm-js#4349]
I don't know who to ask; so I will ask here, seems like a good place.
I tried to create an app (React-Native) which will have Public partition and Private partition using this wonderful package (@realm/react), but I fall short because, I can't seem to find a better way use ``` useRealm ``` hook to get the realm so that I can use it to register a user, as a work around I tried to user Realm SDK from the ```realm``` package, but when I try to retrieve the cloud docs I get empty objects.

better Question will be, how can I achieve this layout:
```
<RealmProvider config={{ schema, sync: {user, partitionValue}}>
   <AuthProvider>
      <RootApp />
    </AuthProvider>
</RealmProvider>

```
or how Can I export user hook (userAuth for authentication status that I can use to set sync) from ```@realm/react```  - ```{createRealmContext}```?

I will appreciate any help.
Greetings from Tanzania 😊

**Comment by tomduncalf** [comment]
Hey @reanzi! 

Thanks for raising this – working with sync and the Realm React package is not currently as easy we'd like it to be, this is something we are actively working on improving right now.

I am preparing an example of how you can currently work with sync with Realm React, I will share it with you once it's ready tomorrow!

**Comment by reanzi** [comment]
Hello @tomduncalf 
Thanks for your answer, I will be waiting brother. 
As of now, I'm able to save data locally just fine though it doesn't sync with the cloud.
This ```@realm/react``` is a massive help indeed :)

**Comment by reanzi** [comment]
I found this ```@realm.io/react ``` at ```https://www.npmjs.com/package/@realm.io/react``` via a tutorial in this [repo by  Maxime](https://github.com/MaBeuLux88/ReactNativeMaximeDemo/tree/step_2)
I tried it and it works, but upon visiting the package in npm , it's deprecated so we're advised to use ```@realm/react```

So I'm still sitting on my hand

**Comment by tomduncalf** [comment]
Hey @reanzi, I hadn't seen Maxime's example, that's great – it's pretty much exactly what I was creating :) 

`@realm.io/react` is just the old name for `@realm/react` – we have migrated to `@realm/react` so you should use that instead. It will be functionally identical.

Is your original issue now solved or do you still need some assistance with working with sync?

**Comment by reanzi** [comment]
> Hey @reanzi, I hadn't seen Maxime's example, that's great – it's pretty much exactly what I was creating :)
> 
> `@realm.io/react` is just the old name for `@realm/react` – we have migrated to `@realm/react` so you should use that instead. It will be functionally identical.
> 
> Is your original issue now solved or do you still need some assistance with working with sync?

Not yet, Everything seems to work locally though, only the sync part. ****I still need assistance on this**!**

Maxime repo is ```https://github.com/MaBeuLux88/ReactNativeMaximeDemo```

I appreciate your help, please let me know if you got something, at the meantime I'm continuing locally.
I just love this ```@realm/react``` package to let go, so I will be waiting

**Comment by tomduncalf** [comment]
I've created an example showing the changes that I needed to make to our [Realm React example app](https://github.com/realm/realm-js/tree/master/packages/realm-react/example) in order to make it support sync with email/password authentication. Hopefully the pull request shows the changes fairly clearly: https://github.com/realm/realm-js/pull/4354/files

The way I chose to approach it is to create a top-level `AppWrapper` component which handles creating the Realm app and authentication. If the user is successfully authenticated, we render the `App` component, otherwise we render a login screen. There are of course other ways you could structure it to achieve the same result, but hopefully this demonstrates the fundamentals. Maxime's example is more or less the same, except his `AppWrapper` is in the same file as the rest of the `App`.

We are looking to create extra hooks in Realm React to make working with sync simpler, so we will update you when we have something for you to try if you'd be interested! Equally if you have any thoughts on how you'd like to see this made simpler, please feel free to share them.

**Comment by reanzi** [comment]
Thanks, I'll check it out.
And yes, I would love to try anything you'll come up with.
Thanks for your efforts.

**Comment by tomduncalf** [comment]
I will close this issue – please feel free to raise a new issue if you encounter other problems, or let me know in here if you are still having issues.
