### ISSUE TITLE
Feature Request: Add support for native-react-meteor npm plugin

### ISSUE THREAD

**Issue by dredgerman** [realm/realm-js#435]
Hi,
Is there any way that support can be given to bridge the gap between native-react-meteor plugin which allows integration of meteor calls in native-react, which links to a mongodb backend,

This is a final step between standard meteor setup with mongo and realm as an offline database,

The reason for this is that a lot of people wish to remain in meteor but the move seems to be on mobile towards react-native and realm-react-native so to close this gap between two systems would be ideal!

If there is a simple way to do this or you have any suggestions or leads for me as a best practice guide then I will chase this up myself given your feedback,

https://www.npmjs.com/package/react-native-meteor

Is it simple to incorporate backend services with Realm?  And if so what Realm reference or guidelines should I be following for issues such as, when to update realm on device, how to manage behaviour of realm when online/offline, issues caused by reactivity of meteor etc, any advice you can give would be greatly appreciated....

**Comment by appden** [comment]
@dredgerman Thanks for this suggestion. It's something we can look into, but will probably need to hear from enough developers interested in this kind of integration. Right now, `react-native-meteor` relies deeply on [minimongo-cache](https://github.com/petehunt/minimongo-cache) for offline caching. In order to use `Realm` with `react-native-meteor`, a fork of `minimongo-cache` would need to be created that mimics its API, but persists data with `Realm` rather than storing everything in memory. I'm not sure this is a worthwhile undertaking to be honest.

**Comment by JulianKingman** [comment]
I'm creating a bridge in my experimental `realm` branch here https://github.com/DesignmanIO/react-native-meteor-redux#realm
There's an example you can test.

**Comment by balibou** [comment]
It could be awesome if we could make work react native - realm - meteor, and solving performance issues !
