### ISSUE TITLE
problem where when I publish my application to the playstore with an update in the schema realm

### ISSUE THREAD

**Issue by ubay1** [realm/realm-js#4420]
hi, I have a problem where when I publish my application to the playstore with an update in the schema realm, the error is

com.facebook.react.common.JavascriptException: Error: Migration is required due to the following errors:

how to solve it ?

**Comment by fronck** [comment]
@ubay1 Is that the whole error message?  There's no elaboration on what the following errors are?

As per your issue:  are you using Sync, or is this a local database?

**Comment by ubay1** [comment]
local database.

**Comment by tomduncalf** [comment]
Hi @ubay1, it sounds like you have made a change to your schema which requires a manual migration, because Realm cannot automatically migrate it (e.g. renaming or deleting a field). You can read more about migrations [here](https://docs.mongodb.com/realm/sdk/react-native/fundamentals/schema-versions-and-migrations/#std-label-react-native-migrations) and more about [modifying your schema](https://docs.mongodb.com/realm/sdk/react-native/examples/modify-an-object-schema/#std-label-react-native-modify-an-object-schema) here. 

Please let me know if you need further assitance.
