### ISSUE TITLE
Realm sync non-user data

### ISSUE THREAD

**Issue by anietieasuquo** [realm/realm-js#4424]
### How frequently does the bug occur?

All the time

### Description

I want to sync non-user data, but the `sync` passed to `Realm.open({})` requires a user object to be passed.

In my app, there are some data created prior to a user sign-in, so it doesn't belong to an actual user, but needs to be stored on the Realm DB.

How do we do that

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Try to open a realm without passing a user object.

### Version

10.11.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

MacOs

### Build environment

Which debugger for React Native: ..

**Comment by fronck** [comment]
@anietieasuquo There's an anonymous login mode available (see [here](https://docs.mongodb.com/realm/sdk/node/quick-start/#authenticate-a-user) and [here](https://docs.mongodb.com/realm/authentication/anonymous/#std-label-anonymous-authentication)).  Would that solve your problem?

**Comment by anietieasuquo** [comment]
Hi @fronck 
When I use the anonymous login, I get an error;
`Realm sync error has occurred. Session: {}, error: {"name":"Error","message":"Bad changeset (UPLOAD) - request logs URL:?","isFatal":true,"category":"realm::sync::ProtocolError","code":212,"userInfo":{}}`.

The logs do not provide any useful pointers, here's the request log on Mongodb web;

> translator failed to complete processing batch: failed to update resume token document: client is disconnected

Any ideas?

**Comment by ianpward** [comment]
Looks like your user does not have a valid token or is expired. Be sure to clear your local state on the client now that you are doing Anonymous login as previous user tokens are cached locally for access.

**Comment by anietieasuquo** [comment]
I think this will be a problem. 
My app allows users to authenticate in two ways; email/password with Realm, or connect crypto wallet. So when a crypto wallet is connected I want to save that connection on realm for analytics, so I create an anonymous user each time I want to save the wallet connection on Realm.

So if Realm keeps an authentication cache then this would be a problem.

**Comment by ianpward** [comment]
Not quite. You can use allUsers() to iterate through users and select the one you want and switch realms appropriately (ie. the anonymous one OR the logged in one) - 
https://docs.mongodb.com/realm-sdks/js/latest/Realm.App.html#allUsers

Typically, for an app like yours, you would on app startUp 
A. Anonymous Login with Realm Cloud
B. Login with a randomly generated user/pass in code so that the user is known by your backend system (for tracking) 

From there, once the user chooses to login and create an account you can link their identities - 
https://docs.mongodb.com/realm/sdk/node/advanced/link-identities/

Happy to keep answering your questions but the Github is typically reserved for bugs related to the local only database. Take it to our  https://forums.realm.io/ - and I'm happy to keep answering your questions
