### ISSUE TITLE
Node.js worker_threads inconsistent behavior throwing error IncorrectThreadException and "Realm accessed from incorrect thread"

### ISSUE THREAD

**Issue by GitMurf** [realm/realm-js#4434]
### How frequently does the bug occur?

All the time

### Description

I am trying to create a very simple worker thread in my node js app. It seems to partially work but during Write() functions it will most of the time throw an error about `Realm accessed from incorrect thread`. I am not sure what better way to explain / demonstrate it then actually re-creating it in Replit so here is my simple example code. You can either run it directly there or can fork it to play around (I don't care if you mess up my replit as I have it backed up).

Here is the exact error:

![image](https://user-images.githubusercontent.com/64155612/159191224-2a14297b-e3f2-4da2-a716-9f4dfd1b7e36.png)

It also occurs the very first time you run it before the realm db is created. On Realm.open() the first time, since it has to create the DB, it gives this same error. It seems to be when trying to write/modify.

The very odd thing is that often times the new item actually does get created in the database even though it gives the error (and doesn't finish with the postMessage logs). You can see this by running it several times and looking at the "Task count: x" I have in the postMessage logs.

Here is the replit: https://replit.com/@ShawnMurphy/RealmWorkerTest-for-GitHub#index.js

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

See the replit here: https://replit.com/@ShawnMurphy/RealmWorkerTest-for-GitHub#index.js

### Version

10.13.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Windows, Mac and Replit online

**Comment by GitMurf** [comment]
If you want to see the code directly here (same code from the Replit) here it is:

### index.js

```js
const { Worker } = require("worker_threads");
//Turn this off for testing as the write() is what is causing error
const writeToDb = true;
const dateNum = Date.now();
const worker = new Worker("./realmWorker.js", { workerData: { newId: dateNum, writeOn: writeToDb } });
//Listen for a message from worker
worker.on("message", result => {
    console.log(`Worker thread msg: ${result}`);
});
```

### realmWorker.js

```js
const { parentPort, workerData } = require("worker_threads");
const Realm = require('realm');

async function addToRealm() {
    parentPort.postMessage(`Start of realm function`);
    const TaskSchema = {
        name: "Task",
        properties: {
            _id: "int",
            name: "string",
            status: "string?",
        },
        primaryKey: "_id",
    };
    const realm = await Realm.open({
        path: "dbTest.realm",
        schema: [TaskSchema],
    });
    parentPort.postMessage(`RealmDB Opened`);
    const taskCtr = realm.objects("Task");
    parentPort.postMessage(`Task count: ${taskCtr.length}`);
    try {
        let newTask;
        function createTasks() {
            newTask = realm.create("Task", {
                _id: workerData.newId,
                name: `${workerData.newId}: GO SHOPPING`,
                status: "Open",
            });
        }
        if(workerData.writeOn) {
          parentPort.postMessage(`Before writing...`);
          realm.write(createTasks);
          parentPort.postMessage(`After writing...`);
        } else {
          parentPort.postMessage(`Skipping write operation...`);
        }
    } catch (err) {
        console.log(`Realm Error: ${err}`);
    } finally {
        // Remember to close the realm
        realm.close();
    }
}

(async() => {
  await addToRealm();
  parentPort.postMessage(`THE VERY END`);
})();
```

**Comment by GitMurf** [comment]
One thing to note, the super weird thing is you can rapid fire keep running it and every 5-10 runs it will work and you will see this task count go up... but most the time the task count stays the same. Occasionally it won't even give you any errors.

![image](https://user-images.githubusercontent.com/64155612/159191606-3810fc62-d2b2-4c2b-b825-ccf990fffdc7.png)

**Comment by tomduncalf** [comment]
Hi @GitMurf, thanks for the report. I'm not familiar with how Node's `worker_threads` work so will need to do some research, it might be that the way it works is not currently supported by Realm JS. I'll update you once I've found out more.

**Comment by GitMurf** [comment]
> Hi @GitMurf, thanks for the report. I'm not familiar with how Node's `worker_threads` work so will need to do some research, it might be that the way it works is not currently supported by Realm JS. I'll update you once I've found out more.

Thanks a lot! Hopefully my repl will make it easy / clear too what I am trying to do and how the worker_threads are implemented. Let me know if you have any questions.

**Comment by GitMurf** [comment]
@tomduncalf here is another odd thing. Testing on my local machine this video (with audio) shows how if I have Realm Studio open with my DB loaded and run my app with Realm on the worker thread then it still quits the worker immediately after the write() execution but it still actually writes/adds those items to the RealmDB. BUT the key "odd" thing you will see in this video is if I close the DB from Realm Studio and then continue to write to it with my node app, they actually do not write/persist to the DB! If you open Realm Studio back up and load the DB you will see nothing has been added since the last time I closed Realm Studio. Then I can immediately start writing again with my node app and you will see the items added to the DB in Realm Studio.

https://user-images.githubusercontent.com/64155612/159327548-f9accf2a-5675-46e5-b2b1-d627e2ff15fb.mp4

**Comment by tomduncalf** [comment]
Hey @GitMurf, thanks for all the details!

I have done some investigation, and the issue is fundamentally that we don't support multi-threaded use of Realm JS – we assume you will only be accessing the Realm from a single thread, as is usually the case for JS apps.

More specifically, what is happening when using `worker_threads` to access Realm from a worker thread, as in your example, is that the Realm is opened on, and interacted with, from the worker thread, rather than the main Node thread. However, our Node JS scheduler currently only supports running on the [default loop](https://github.com/realm/realm-core/blob/master/src/realm/object-store/util/uv/scheduler.hpp#L33), which corresponds to the main thread. 

When you write to the Realm (from the worker thread), Realm will [schedule a call to notify()](https://github.com/realm/realm-core/blob/master/src/realm/object-store/impl/weak_realm_notifier.cpp#L40-L46) to trigger any notifications, and this call will run on the main thread (because the scheduler only supports running on the main thread). `notify` in turn calls [`verify_thread()`](https://github.com/realm/realm-core/blob/master/src/realm/object-store/shared_realm.cpp#L1111) to check that it is being called on the same thread that the Realm was created on, in order to avoid threading issues, and this check [fails](https://github.com/realm/realm-core/blob/master/src/realm/object-store/util/uv/scheduler.hpp#L69) and [throws an exception](https://github.com/realm/realm-core/blob/master/src/realm/object-store/shared_realm.cpp#L554), because the Realm was opened on the worker thread but `notify` is being called from the main thread.

I can't see any way round this other than ensuring that you only interact with the Realm from the main thread rather than a worker thread. It might be that it is possible for us to support `worker_threads` in future, so I will create an issue for us to investigate this, but I can't give any timeframe for when we might get to this. Hopefully you are able to work around this for now!

Thanks,
Tom

**Comment by SevenZark** [comment]
I must admit, I'm a little surprised that this would be considered too trivial to support for now. To me this is a major shortcoming. The point of using a db over flat files is efficiency in handling a large amount of records. But since I cannot do this (I get the same error as in the OP) I am forced, instead, to load thousands of records for an entire realm, stringify them as one monolith, and send that monolith to the worker thread. Thus, I lose any benefit of using Realm in the first place. 

And I HAVE to put the processing I need to do in a worker thread, because if I don't, the main app thread is blocked for far too long, resulting in an unresponsive, blank-screened app for many, many minutes.

Am I just missing something? Because as it stands, it seems that Realm is useless in my app and I might as well just store data in JSON files since I'm forced to deal with monolithic data objects instead. I MUST be missing something because this seems like such a deal-breaker for any data-intensive app...?

**Comment by GitMurf** [comment]
I really love Realm! But I would love to know a better solution as well, or if someone can recommend a better design pattern? Because I as well find myself often pulling realm results, having to stringify the results into POJO so I can send to worker thread to do processing, then send back. It feels like there has to be a better way than the way we are doing it ;) @SevenZark is this similar to what you are finding yourself having to do?

Realm is super fast... but it gets offset with often having to stringify way too often and pass back and forth to worker threads.

**Comment by SevenZark** [comment]
> @SevenZark is this similar to what you are finding yourself having to do?

Yes, that's my issue. it's pointless using a database engine if you're going to flatten the data into huge objects and past those around to threads. You might as well just read JSON from flat files at that point. It's strange to me they react to supporting worker threads with "meh." There are cases when we absolutely have to use them to unblock the main thread. This is part of life writing software for Node. To refuse to support it is to almost directly state you officially do not want your db platform to be a full solution for Node. And for all I know, that might be the case. Maybe there are just too few people using the Node SDK, so it can't be a priority? I don't know. All I know is, I will probably have to abandon Realm for this project, due to this nasty surprise.
