### ISSUE TITLE
Massive performance issue when updating items by looping through each object when using a filter

### ISSUE THREAD

**Issue by GitMurf** [realm/realm-js#4436]
### How frequently does the bug occur?

All the time

### Description

I am not sure why this is but it seems like when using `.filtered()` before looping through the results to update values it takes exponentially longer to update objects.

Here is a simple setup of creating 100k items in Realm (takes 1.2 seconds):

```js
const Realm = require('realm');

async function startApp() {
    const Block = {
        name: 'Block',
        primaryKey: '_id',
        properties: {
            _id: 'string',
            name: 'string',
            description: 'string',
            type: 'string',
        },
    }

    let realmDB;
    try {
        realmDB = await Realm.open({
            path: 'dbtest/realmDB.realm',
            schema: [Block],
        });

        console.time('createBlocks');
        realmDB.write(() => {
            for (let i = 0; i < 100000; i++) {
                let newBlock = realmDB.create('Block', {
                    _id: i.toString(),
                    name: 'Block ' + i,
                    description: 'Block ' + i + ' description',
                    type: 'THING',
                });
            }
        });
        console.timeEnd('createBlocks');
    } catch (error) {
        console.log(`RealmDB initialization error: ${error}`)
    } finally {
        realmDB.close();
    }
}

startApp();
```

And now here I try to update all the 100k blocks and it runs for several minutes and does NOT complete for me. Below I added an exit after updating 5,000 items so it doesn't freeze on you and that 5,000 items takes over 50 seconds for me:

```js
console.time('updateBlocks');
let blocks = realmDB.objects('Block').filtered('type == "THING"');
let ctr = 0;
realmDB.write(() => {
    blocks.forEach((block) => {
        ctr++;
        if (ctr > 5000) { return }
        block.name = `___Block content id: ${block._id}`;
    });
});
console.timeEnd('updateBlocks');
```

Now simply remove the `.filtered()` and loop through all blocks and it updates ALL 100k blocks in under 2 seconds:

```js
//let blocks = realmDB.objects('Block').filtered('type == "THING"');
let blocks = realmDB.objects('Block');
```

What could be going on? Can you not use the .filtered() item when looping to update a bunch of items?

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

See above main post...

### Version

10.13.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Windows 11 and Mac

**Comment by GitMurf** [comment]
Ok it looks like if I change to the following then it works ok. Any idea why? This means I have to loop through my results twice which isn't ideal.

```js
    console.time('updateBlocks');
    let blocks = realmDB.objects('Block').filtered('type == "THING"');
    let myNewBlocks = [];
    for (let i = 0; i < blocks.length; i++) {
        const block = blocks[i];
        myNewBlocks.push(block);
    }
    realmDB.write(() => {
        myNewBlocks.forEach((block) => {
            block.name = `NEWER-Block content id: ${block._id}`;
        });
    });
    console.timeEnd('updateBlocks');
```

**Comment by GitMurf** [comment]
Here is an example from the docs… this is exactly how i was doing it in my OP, and this causes the perf issues on my! updates.

https://docs.mongodb.com/realm/sdk/react-native/examples/read-and-write-data/#bulk-update-a-collection

[image](https://user-images.githubusercontent.com/64155612/159458388-b0fdaae9-1e5c-46ea-a2cc-d4b2869b9222.png

**Comment by tomduncalf** [comment]
Hi @GitMurf, thanks for the report. I was able to confirm this issue locally (https://github.com/tomduncalf/4436-slow-filter). We will need to do some investigation into what is causing this. We'll update this issue when we have more information to share.

Thanks!

**Comment by GitMurf** [comment]
> Hi @GitMurf, thanks for the report. I was able to confirm this issue locally (https://github.com/tomduncalf/4436-slow-filter). We will need to do some investigation into what is causing this. We'll update this issue when we have more information to share.
> 
> 
> 
> Thanks!

Awesome! Thanks for the quick response :)

**Comment by aguycalled** [comment]
I am also seeing this issue, any expected time for a fix?

**Comment by tomduncalf** [comment]
Hi, we've done some investigation into this and this is actually "working as expected".

When you call `.filtered` on a `Realm.Results`, under the hood this creates what we call a "table view" – i.e. a filtered view of the underlying table. Computing this filtered view is quite expensive, but once it has been computed once, we can continue using the cached result, so e.g. a `for` loop just logging out the data is fast. However, if the underlying table's data changes, we need to recompute the filtered view, as which data is "in view" may have changed as a result of the update.

In your case, you are updating an object in the database every iteration: `block.name = ...`. This means that every iteration, the filtered table view has to be recomputed as the data in the table has changed (so Realm needs to check if your change modified which objects are "in view"). This is a relatively expensive operation to perform every iteration, hence why you see performance issues doing this. 

When you do not filter the results, there's no table view required – we just access the table directly, so this recomputation is not needed and you don't see the same performance issue.

The good news is that you can work around this by iterating over a [snapshot](https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.Collection.html#snapshot) of the filtered data instead. This means that the collection you are iterating over will be not be updated as a result of any changes you make, but is instead a snapshot of it at the time you did the query, which is usually what you actually want. 

There are two ways to achieve this. One is to explicitly take a snapshot of the data before you iterate over it:

```
const blocks = realmDB.objects("Block").filtered('type == "THING"').snapshot();
// then later
blocks.forEach(block => {
// ...
```

Or the other is to use `for ... of` or `for ... in` to iterate over the results, as under the hood, Realm JS calls `snapshot` on the collection when you do this, in order to prevent unexpected issues with the collection changing while iterating over it. `for ... of` is generally the preferred style in modern Javascript.

```
const blocks = realmDB.objects("Block").filtered('type == "THING"');
// then later
for (let block of blocks) {
// ...
````

One other thing worth mentioning if you are looking for maximum performance when iterating in JS is that `forEach` is actually quite slow. You should find that a plain `for` loop or using `for ... of`/`for ... in` is faster.

Thanks,
Tom

**Comment by GitMurf** [comment]
@tomduncalf thank you for the update, great explanations and the solution(s). Would you agree this could be something better documented and maybe mentioned in the docs example I referred to in this message above? https://github.com/realm/realm-js/issues/4436#issuecomment-1074987361

A few things to note responding to your points (which all make sense):

1) the example on your website docs uses forEach. I’m sure for simplicity sake. But maybe good to update to use for…of as a best practice for performance like you said.

2) maybe that example (and others) on your website should either add a note about using snapshot() on the filter OR may in fact be better to just add the snapshot() as the default, as I think the intent of that example in your docs is for iteration and updating of data and likely not wanting or needing to reload the view every time (creating perf issues).

Here is the example again I am referring to (and screenshot below): https://docs.mongodb.com/realm/sdk/react-native/examples/read-and-write-data/#bulk-update-a-collection

**Comment by tomduncalf** [comment]
Hey @GitMurf, 100% agree this could be better documented and we were discussing internally how we could best do that without overcomplicating things. 

Where do you think it would be heplful to see a note on this in our API docs/Typescript docs, if anywhere? I guess it could be added to the docs for `filtered`, for example.

Thanks very much for pointing out that the current documentation is incorrect – I didn't realise we had an example of this on there. I will pass this on to our docs team and hopefully they can update it soon.

**Comment by GitMurf** [comment]
@tomduncalf yes I think 3 things could be done to make this the most clear:

1) update the example in your docs as mentioned above and as you already alluded to passing to the docs team.

2) adding a blurb summarizing in the docs for the filtered method/function here: https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.Collection.html#filtered

3) similarly adding a bit more detail / context (explaining the value of using on .filtered() stuff when updating objects) in the snapshot docs method/function area here: https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.Collection.html#snapshot

I think item 1 above is probably the most important for people just starting to use Realm for the first time because examples is usually the best place to get your feet wet. I think probably showing an example with and without snapshot and explaining what that means for performance (as you have above) would be ideal.

Then maybe linking to the example(s) for both filtered and snapshot docs (2 and 3 above) would be helpful.

Thanks again for the help and clearing things up!

**Comment by tomduncalf** [comment]
Great, thanks for your input on this! I'll pass it on to our docs team and when the changes have been made I'll let you know if you'd like to take another look :)

**Comment by GitMurf** [comment]
@tomduncalf one other question on my end. At a high level am I using the right approach for filtering and iterating to bulk update objects in Realm? Or is there an alternative route I could take and/or a “better way”? I am talking the full process of starting with `realmDB.objects('Block')`… adding the `.filtered(')` … iterating through the results … updating the results within the iteration (loop).

Or is this the “right/best” approach to be taking?

**Comment by GitMurf** [comment]
And I guess as well, having all of the updates done within a single `realmDB.write` operation?

**Comment by tomduncalf** [comment]
Your approach seems fine to me, Realm is designed to perform well with code written "how you'd expect to write it" in general, but I'll check with my team if anyone has any additional feedback on that
