### ISSUE TITLE
Memory leak on realm.objects() and realm.write()

### ISSUE THREAD

**Issue by EloiMarin** [realm/realm-js#4743]
Hello,

I have observed a memory leak in an application. I could boil it down to this minimal reproduction code:

```
const Realm = require("realm");
const { appId, config, jwtToken } = require("./config");

async function main() {
  const app = new Realm.App({ id: appId });
  await app.logIn(Realm.Credentials.jwt(jwtToken));
  config.sync.user = app.currentUser;
  const realm = new Realm(config);

  function leak() {
    realm.objects("FileController").filtered("type = 'toDelete'")[0];
    realm.write(() => {});
    realm.objects("FileController").filtered("type = 'toUpdate'")[0];
    realm.write(() => {});
  }

  setInterval(leak, 1000);
}

main();
```

This program represents the behaviour of that application and it leaks in exactly the same way. Possible optimisations beside, I would expect this code to behave nicely albeit not doing anything uself (in the real application there is a lot of code around those calls and the `write()` callback has an actual implementation but I found that is enough to have an empty callback to reproduce the leak), because no object references are kept around and the runtime should have plenty of time to eventually cleanup memory.

Here I attach two screenshots showing the increase of system memory usage.

Before:
![before](https://user-images.githubusercontent.com/8020768/181535109-71f547d9-df63-45cf-aa00-2c2eeeae1d8b.png)

After (~45 minutes):
![after](https://user-images.githubusercontent.com/8020768/181536301-3300a408-62db-4aca-b385-55f206328bf9.png)

You can see that the system memory usage (`RES`) has increased by about ~90MB. Note also that the javascript heap size has only grown 7MB, so the leak seems to be on the native side. The leak also happens withouth the `--inspect` Node flag, but I wanted to take these screenshots keeping an eye on the Javascript heap size.

It's also worth noting that the leak does _not_ ocurr when working locally, but only in sync mode. Of course I can't disclose the credentials of the connection of this app :) that's why I provide only the snippet above instead of a full project for reproduction.

My main question is: Is there something inherently wrong in the pattern of usage of `realm-js` shown in the example above that should be fixed on the application side? Or is this a legitimate memory leak in `realm-js`?

- Realm version: `10.19.5`
- Node version: `16.16.0`

**Comment by EloiMarin** [comment]
I'm updating the issue with two new behaviours I observed, which might help in debugging:

The following simplified example also leaks, but only when the time interval is short enough (eg., it does _not_ leak with a `1000` milliseconds interval, but it does with a value of `100` or less). Maybe the leak is related to requesting new RPC calls before the previous had time to finish?

```
  // ...
  function leak() {
    realm.objects("FileController");
  }

  setInterval(leak, 10);
```

---

In addition to that, I've observed that the `--max_old_space_size` Node flag can cap the maximum size of the leak in a somehow linear way. For example, setting `--max_old_space_size=10` the memory consumption of the Node process stops increasing at about ~100MB, and when setting it to `--max_old_space_size=20` it goes up to ~150MB (so although the leak is not within the javascript heap, it seems to be somehow related to it).

I tried to look into the source myself but the complexity of this project makes this task way beyond the time I can invest to debug it myself... so any help or suggestion to keep nailing down the problem would be greatly appreciated :)

**Comment by kneth** [comment]
Sorry for the late reply. And thank you for your detailed analysis.

I believe the issue is unrelated to Realm, but is related to how the garbage collection is working.

Consider the following code (`simple-leak.js`):

```js
function leak() {
  const obj = { };
  console.log(process.memoryUsage().heapUsed);
}

setInterval(leak, 10);
```

If you run it with `node simple-leak.js`, you will be a steady increasing number. The reason is that the garbage collector will not kick in before you reach node's memory limit. You can try lower the limit with `node --max-old-space-size=32 simple-leak.js`, and you will see that the number will decrease on a regular interval (when the garbage collector is kicking in) and then grow again.

Now consider the case where you manually call the garbage collector (`simple-leak-gc.js`):

```js
function leak() {
  const obj = { };
  global.gc();
  console.log(process.memoryUsage().heapUsed);
}

setInterval(leak, 10);
```

When you run it as `node --expose_gc simple-leak-gc.js`, you will observe that the number find a stable value after a while.

I believe the rationale is that garbage collection is expensive, and node.js will try to avoid doing it for as long as possible.

**Comment by EloiMarin** [comment]
Thanks @kneth for your answer.

I am expecting indeed to see a sawtooth pattern in the memory consumption of any Node process. But the original application in which this problem was observed, had a memory usage increase for _days_ straight (the app using `realm-js` corresponds to the increasing slope):

![App memory usage](https://user-images.githubusercontent.com/8020768/182600616-ed5e5c78-68c8-42e7-97b2-18f038913cca.png)

So I would expect that the garbage collection has had plenty of opportunities to do its job and reach a stable state by then :P (small corrections can be seen, but they don't seem enough to stabilise the trend). My first post was just trying to isolate the issue, but that's the real problem that was observed.

And the main reason why my client is concerned with this behaviour is because we are not sure if it's safe to deploy such an application into production. From that point of view, can you or someone else in the community confirm that this graphic does represent expected behaviour, and that the application will eventually reach a stable memory usage (without reaching into the gigabyte range... even if this application runs 24/7)? If not, I think relying on the `--max-old-space-size` flag can be an acceptable solution, but I would not consider to `--expose-gc` and call the garbage collector manually as a stable solution for an application in production.

---

Also something interesting when running your `simple-leak.js`: I observe the usual sawtooth pattern, although as time passes the minimum keeps increasing so the process tends to increase its memory usage over time (for example, if the heap size lies between 4-5MB when the process starts, it's maybe around 5-6MB after 15 minutes running although the garbage collector is clearly begin triggered every 5 seconds or so).

**Comment by kneth** [comment]
@EloiMarin In order to explain the graph above, we need to understand how you use Realm. Moreover, it can be interesting to know if the memory usage is correlated with the size of the Realm file.

Realm is using [memory mapping](https://en.wikipedia.org/wiki/Memory-mapped_file), and when the Realm file grows, it is expected that you will see a growth of virtual address space.

Furthermore, Realm is never freeing space in the file but it reuse it later. The implication is that if you delete an object, the Realm file will decrease in size. If you are creating and deleting objects, it could explain the growth as you observe (guessing as there are many unknowns for me).

For an application running 24/7, you could periodically close the Realm, [compact](https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.html#compact) it and open it again (or close and open it with `shouldCompactOnLaunch` in your [configuration](https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.html#~Configuration)).

**Comment by EloiMarin** [comment]
@kneth The application using Realm was mostly idle when that graph was generated, but your explanation is going to be very helpful indeed to understand the memory behaviour of this application.

We will take it into account and move ahead with the development having that in mind. I'll close this issue because I think it doesn't sustain anymore until we try this application more extensively, including your idea about compacting the Realm (and keep an idea on its size when it comes to memory usage).

Thank you!

**Comment by kneth** [comment]
@EloiMarin Don't hesitate to create issues if you have further questions!

**Comment by rajspatel1297** [comment]
Hi all,

I'm facing similar kind of issue with Realm integration in Node.js.  My application is totally offline based. Here is my code:

**Test 1: Creating a global connection and use it in the app**

`
// realm.connection.js
const realmConfig = new Realm({
    path: "db.realm",
    schema: configurationList,
    schemaVersion: constant.appConfig.realm_schema
});

module.exports = {
    realmConfig
}

// realm.db.js
const getConfigurationObject = async (schemaName) => {
    try {
        const realmData = realmConfig.objects(schemaName)
        const data = common.cloneObject(realmData); // even if I remove this line still its creating some memory leak
        return {
            status: true,
            data: data
        };
    } catch (error) {
        console.log("Error***********", error)
    }
}
`
I'm getting following error:
`2022-08-19 06:39 +00:00: terminate called after throwing an instance of '
2022-08-19 06:39 +00:00: realm::AddressSpaceExhausted'
2022-08-19 06:39 +00:00:   what():  mmap() failed: Cannot allocate memory size: 44040192 offset: 0`

I checked my heap usage and memory usage. The heap usage is stable and memory is slowly increasing. After 4 days of running it, it restarts due to the error mentioned above.

![Screenshot from 2022-08-19 11-23-15](https://user-images.githubusercontent.com/87131761/185652709-72f643bf-fddb-42a3-88df-514e7abaf096.png)


**Test 2: Open and close realm in every call of getConfigurationObject().** 

`
// realm.db.js
const getConfigurationObject = async (schemaName) => {
    try {
        const realmConfig = new Realm({
    		path: "db.realm",
    		schema: configurationList,
    		schemaVersion: constant.appConfig.realm_schema
	});
        const realmData = realmConfig.objects(schemaName)
        const data = common.cloneObject(realmData); // even if I remove this line still its creating some memory leak
        realmConfig.close();
        return {
            status: true,
            data: data
        };
    } catch (error) {
        console.log("Error***********", error)
    }
}
`

Using this way creating more RealmObject in the background resulting in heavy memory and heap increase.

![image](https://user-images.githubusercontent.com/87131761/185653778-765a0d84-9bb2-442f-979e-cbb89a9ba3fb.png)

So, these test clearly says that test 1 is better than test 2, but is it the right way?

If so then according to the previous discussion by @kneth, do I need to use --max-old-space-size flag to cop up with memory leak?

**Comment by kneth** [comment]
@rajspatel1297 Changing `--max-old-space-size` will only give you a bit longer time before you run out of memory. Until [online compaction](https://github.com/realm/realm-core/pull/5755) is released, I will suggest that you periodically close your Realms and compact them. It might also be interesting to see if calling `global.gc()` will help you.

**Comment by rajspatel1297** [comment]
Thanks @kneth. I saw some strange things after 2 days. I that possible that the garbage collector automatically handles the cleanup but the memory limit when it triggers is different?

I'm running it without --max-old-space-size. 

Module with 1GB memory
![image](https://user-images.githubusercontent.com/87131761/186169818-7b30e42d-5326-4609-b6fa-e0b81649207e.png)

**Comment by kneth** [comment]
@rajspatel1297 I am not an expert of [node's garbage collector](https://blog.risingstack.com/finding-a-memory-leak-in-node-js/) but my understanding of old and new generations is aligned with your observation. Since garbage collection is an expensive operation, I can imagine that node will try to avoid it for as long as possible.
