### ISSUE TITLE
rnpm link error on Windows

### ISSUE THREAD

**Issue by guoguow** [realm/realm-js#477]
E:\BE\rnsisV1>rnpm link realm
rnpm-link info Android module realm is already linked
rnpm-link info iOS module realm is already linked
rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN 
Please file an issue here: https://github.com/rnpm/rnpm/issues
在安卓模拟器中显示的是missing  realm constructor
开发环境win7的 webstrom，如何解决？

**Comment by appden** [comment]
It appears the `spawn UNKNOWN` error occurs because it attempts to `rnpm link` in iOS support, but you're running on a Windows machine. The `Missing Realm constructor` error means that Android support doesn't appear to have been linked in correctly. Does your `MainActivity.java` include `RealmPackage`?

**Comment by guoguow** [comment]
![image](https://cloud.githubusercontent.com/assets/12043538/15988147/ae7bb3e2-3077-11e6-9108-6fa5dd9c45f1.png)
在mainActivity中已经引入realmReactPackage了

**Comment by appden** [comment]
Can you also check that `new RealmReactPackage()` is being returned from the `getPackages()` method? Will you please share which versions of Android and React Native you're using? Are you getting the `Missing Realm constructor` error only in debug mode, or always?

**Comment by guoguow** [comment]
已经解决了，需要重新在手机端安装app才算是重新编译了，否则是不可以的，因为androi包的更改并没生效

**Comment by alazier** [comment]
Glad you got this resolved (assuming google translate is correct)
