### ISSUE TITLE
Get size of Realm.Results in Bytes. Very useful in Range requests

### ISSUE THREAD

**Issue by jefersoneiji** [realm/realm-js#5113]
### Problem
Hi, ReamlJS team. The current use case i'm facing is related to [``Range`` requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests), more on this next. And i know it's very specific. All i ask of you is to take a quick look into it if possible. 

Basically, range quests use the ``Range`` header to return specific ranges of data from an api. Wich translates into the current scenario: 

* first, getting the realm collection items to know what the app already has ``realm.objects('Tasks')`` 
* secondly (hypothetically), getting the size of ``Realm.Results`{{ from returned array of }}`Tasks`{{. Maybe, }}`realm.objects('Tasks').sizeInBytes`` (returning 100 bytes)
* thirdly, would be possible to use this size in the next request to an api in a manner similar to this ``Range: bytes=100-``

PS: In my project, Realm is fully local meaning zero connection, sincronization or serveless operations. All local.

### Solution
Nothing really fast to implement. All i can think of is learning the realmJS code base and create a pull request here. 

### How important is this improvement for you?
Fairly niche, but nice to have anyway.

**Comment by codeLearnerrr** [comment]
@kneth thank you for taking the time for answering. 

- ``I guess you are implementing your own version of sync 😄``
The way the feature was described sounds as realmsync at first sight. What would make this "new realmsync" different is the following. Currently the project back-end is decoupled from any realmsync features. So for simplicity ``sizeInBytes`` feature request was created.

- `` First, you get all the objects (realm.objects('Tasks')). Due to Realm's zero-copy principle, this is a rather cheap operation (time and space).`` 
Alright, nothing to add on this step. 

- ``Secondly you wish to send a certain amount of data to your server. Currently you cannot slice your data in units of bytes, but you could use Realm.Results#slice and serialize them before sending them to the server: JSON.stringify(objects('Tasks').slice(10, 20))``
Yes, i thought this approach before opening this feature request. Parsing 100.000 rows or more sounds very expensive to hardware (synchronously). Plus the server would need to parse every single collection back to JSON  for every user. And the data already is in the required format, why handle all the trouble to parse it before sending and then parse it back in the server instead of just using ``sizeInBytes``?

- ``Thirdly, you need a counter to keep track of what you have transferred. This will require that you can add offset and size as parameters to your HTTP request.``
Nothing to add on this step. 

Is ``sizeInBytes`` feature possible or likely to be in realmjs team roadmap?

Best regards.

**Comment by codeLearnerrr** [comment]
Well, based on the lack of agile response. I'm interpeting that this is issue is somehow abandoned by the maintainers. So i'll close it.

**Comment by codeLearnerrr** [comment]
@kneth alright. Thank you for being thoughtful about the feature. In the end the solution i could think of was to use android/ios native api to download data from back-end. Then, this data was persisted as a file .json for instance on the phone. Because .json is a file, the native api already measures its size in bytes/megabytes. Based on this, was just a matter of using this file size in the request. And only when the file is completely downloaded, its persisted in realm.
