### ISSUE TITLE
Failure to detect object property changes with Realm.addListener() 

### ISSUE THREAD

**Issue by Calhistorian** [realm/realm-js#5207]
### How frequently does the bug occur?

All the time

### Description

**Expectations**

Given a collection listener:
```
Realm.objects('objectCollection', addListener((objects, changes) => {(
    ... // react to changes logic
)};
```

I would expect being able to compare `changes.oldModifications` to `changes.newModifications` in order to determine what properties have been modified for the given Object from the objectCollection as the api docs suggest. However, I am unable to identify the differences of a known property change. My only guess is that my execution is wrong. Is this a known limitation of collection listeners?

### Can you reproduce the bug?

Yes, always

### Version

10.22

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS 13.1

**Comment by takameyer** [comment]
@Calhistorian The `changes` return indexes to what has been modified.  `old` and `new` are used, in the case of a deletion, to know what indexes are modified before and after the deletion, as this would cause the index to change.  According to the [documentation](https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.Collection.html#addListener):

> `deletions` and `oldModifications` are indices into the collection before the change happened, while `insertions` and `newModifications` are indices into the new version of the collection.

In any case, we have had many discussions about the possibility of providing stale data in order to be able to compare changes.  This would be similar to `prevProps` and `newProps` in `React.memo`.  At this time, it is not available, but hopefully we will get that implemented in the near future.

However, you can [register a listener](https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.Object.html#addListener) on each object, and this will provide a list of the properties that have been changed when fired. 

> I would expect being able to compare changes.oldModifications to changes.newModifications in order to determine what properties have been modified for the given Object from the objectCollection as the api docs suggest.

Can you provide a link to the documentation in question?  I would like to make sure this is clear for others.
