### ISSUE TITLE
Infinity conversion discrepancy between Node versions (14 vs 16)

### ISSUE THREAD

**Issue by Frans-L** [realm/realm-js#5339]
### How frequently does the bug occur?

Always

### Description

While I was upgrading to the newer Node version, I found an interesting but minor bug.

When using Node 14, `Infinity` will be converted into `-9223372036854776000`. 
When using Node 16, `Infinity` will be converted into `9223372036854776000`. 

I haven't experimented with whether the behavior also differs also inside different platforms, e.g. iOS vs Android. 

This happens with both Realm 10 & 11. 

Demo:
```ts
import Realm from "realm";

describe("Realm's corner-cases", () => {
  it("Int field accepts Infinity", async () => {
    const ExampleSchema = {
      name: "Example",
      properties: {
        id: "int",
        number: "int",
      },
      primaryKey: "id",
    };

    const realm = await Realm.open({
      inMemory: true,
      schema: [ExampleSchema],
    });

    let obj;
    realm.write(() => {
      obj = realm.create("Example", {
        id: 1,
        number: Infinity,
      });
    });

    // passes with Node >= 16
    expect(obj.number).toBe(9223372036854776000);
    // passes with Node 14
    expect(obj.number).toBe(-9223372036854776000);
  });
});

```

Note that this could be also **Node**'s breaking change, which just happens inside Realm.  

### Can you reproduce the bug?

Always

### Version

Realm 10, 11

### Platform OS and version(s)

Node, at least.

### Build environment

MacOs 12.5 (M1 Pro)

**Comment by Frans-L** [comment]
When running the same test in GitHub CI (Linux container) using Node 16, `Infinity` is converted to `-9223372036854776000`. So it seems like this is also dependent on the operating system, not just the Node version.

**Comment by kneth** [comment]
@Frans-L Thank you for reporting.

Without creating a test to reproduce it, I will say that you are correct.  In the past we were using JSON to transport object to the Chrome debugger (for React Native), and since JSON doesn't support NaN and Infinity, we couldn't support them. We explicitly check for NaN in the [conversion from JS to C++](https://github.com/realm/realm-js/blob/master/src/node/node_value.hpp#L240-L250).

Since we have removed the support of the Chrome debugger, I believe we can lift this limitation and support both NaN, Infinity and -Infinity (for `float` and `double` properties).

**Comment by kneth** [comment]
Realm JS version 12 changes how we handle numbers. The `int` Realm type is treated as [BigInt](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-bigint-objects) and cannot be infinity (neither in Realm nor JavaScript). On the other hand, the Realm types `float` and `double` are floating-point numbers where infinity is a valid value.

To clarify, we have create #6623 based on the example above.
