### ISSUE TITLE
Revisit thread ID changes

### ISSUE THREAD

**Issue by bdash** [realm/realm-js#552]
In realm/realm-object-store#118 it was mentioned that the changes to how a thread ID is computed, originally made in #480, don't appear to be the right way to solve the problem they were intended to solve:

> There's not a lot of information in the original PR to explain why the change was made (realm/realm-js#480). From looking at the realm-js code, I think the problem was related to realm-js's assumption that there's a single JavaScript context per thread. `RealmClass<T>::constructor` stashes the JavaScript context in `Realm::m_binding_context`. If the thread a `Realm` instance belongs to exits and its identifier is reused before the `Realm` instance is deallocated, a new thread calling `RealmClass<T>::constructor` can get back the existing `Realm` instance, and will find that it is associated with a different JavaScript context than it expects.
> 
> Changing the definition of thread ID doesn't seem like the right way to fix that issue.

We should find another way to address this that doesn't require changing the definition of a thread ID.

**Comment by bdash** [comment]
Ari and I looked into this briefly on Tuesday. Our current theory is that the JS binding may be leaking `Realm` instances in the scenario related to #480 (refreshing the app while Chrome debugger is attached). I intend to investigate this angle further once my schedule is more amenable to it.

**Comment by appden** [comment]
I can hopefully shed some light on this. The issue was that a `SharedRealm` would be kept alive for some time after its thread was destroyed due to the GC collecting on another thread. During this time it was still alive, a new thread was created with the **same thread id** and would get back that same `SharedRealm` since it is cached by thread id (see `RealmCoordinator::get_realm()`). The problem with that is the `RealmDelegate` (`BindingContext` subclass) held by the `Realm` is not fresh for the new JS context.

Lots of other subtle issues can occur through thread id reuse. For instance, a `List` or `Results`

**Comment by bdash** [comment]
Thanks for the extra context. I'll keep it in mind when I revisit this.

> Lots of other subtle issues can occur through thread id reuse.

The object store uses the thread ID to enforce our thread confinement requirements that are intended to ensure that objects cannot be used from multiple threads simultaneously. A thread being destroyed and a new thread being created with the same thread ID doesn't violate thread confinement, since only one of the two can ever exist at a time. This is only a problem for realm-js because it stashes state specific to a JavaScript context into the `BindingContext` field of the `Realm` instance.

I think more generally that what realm-js wants is for Realm objects to be confined to a JavaScript context, rather than a thread. JavaScriptCore, and I assume V8, doesn't care which thread you work with a context on so long as you ensure that only a single thread is working with it at a time.

**Comment by appden** [comment]
Yes, it would be nice to generalize how Realm objects are confined, since confining access to the either the JSC context group or v8 isolate would really be ideal. Likewise, it would be nice to confine access to Cocoa Realm objects by GCD queue, for instance.

I think some assumptions are seriously violated when a Realm object is allowed to transfer from a dead thread to newly created thread with the same id. Most of the time it's fine, since like you said, it's all about avoiding concurrent access. But if an app creates create a Realm on new thread, it would reasonably expect to get a brand new `BindingContext` rather than one kept alive from the previous thread.
