### ISSUE TITLE
Testing with mocha, Error: Illegal constructor in native code

### ISSUE THREAD

**Issue by shkyang** [realm/realm-js#565]
I'm using the instructions here to test with mocha: https://github.com/realm/realm-js/issues/521

I am seeing an error when I on write(), I'm only seeing this when I test, the app (ios) works.

Here's what my test is doing:

```
import Realm from 'realm';
class CurrentUser extends Realm.Object {}
CurrentUser.schema = {
    name: 'CurrentUser',
    properties: {
        username:  'string'
    }
};
export default new Realm({schema: [CurrentUser, User, Test, Athlete, Team]});

// this goes in the describe block
       realm.write(() => {
            currentUser = realm.create('CurrentUser', {
                username: 'hi'
            });
        });
```

when I run it, I get:

`
try realm:
     Error: Illegal constructor
      at Error (native)
`

**Comment by fealebenpae** [comment]
Hey @shkyang, I tested this and it appears that extending `Realm.Object` in node break because `Realm.Object` doesn't behave like a constructor function.

You don't need to explicitly derive from `Realm.Object` for your schema to work anyway, but I will look into what's causing this as it works fine on `JavaScriptCore`.

**Comment by shkyang** [comment]
Hi @fealebenpae, 

Thanks for the answer. Your suggested approach of not extending Realm.Object works for me. I'm also curious to see your fix for the issue.
