### ISSUE TITLE
Only need app-id to create users? Security risk?

### ISSUE THREAD

**Issue by j-medinformatics** [realm/realm-js#5717]
### Discussed in https://github.com/realm/realm-js/discussions/5716

<div type='discussions-op-text'>

<sup>Originally posted by **j-medinformatics** April  8, 2023</sup>
Am I getting this right? 

Assuming: 
- an app has "Email Password Auth", and "Send a confirmation email" turned on
- an attacker gets the APP-ID, which is: displayed on Realm UI, part of the HTTPS end points and included in the real_config file.

then the attacker could:

```
  const app = Realm.getApp('APP-ID');
  app.emailPasswordAuth.registerUser({
        email: 'tt0673523@gmail.com',
        password: '123123123',
    });
```

Registering the user and obtaining token and tokenId in the registered email.

then:

```
  const app = Realm.getApp('APP-ID');
  app.emailPasswordAuth. confirmUser({
        token: TOKEN',
        id: TOKEN-ID',
    });
```

Meaning that an attacker only needs the APP-ID to freely create app users.</div>

**Comment by kraenhansen** [comment]
@j-medinformatics please clarify how you view this as a potential security risk? If you want to do additional checks (such as the email has to be on a certain domain name etc.) you can use a confirmation function instead of a simple confirmation email. If you want even more control over who can create users in your app, you can alternatively use a third party service in combination with the JWT / custom token authentication provider.
