### ISSUE TITLE
Realm.write() callback/success

### ISSUE THREAD

**Issue by Everhusk** [realm/realm-js#594]
Is there a way to pass a callback to realm.write() or know when the write has been completed successfully?

**Comment by alazier** [comment]
Writes in Realm are synchronous, so you can simply call a callback after the write to indicate success. On failure a write will throw an exception. You can wrap your write in a try/catch and call a callback from the catch block to indicate error. In general internal errors will almost never happen and would be indicative of more serious issues on a device - more commonly a write will fail or be cancelled due to user code in the write block throwing an exception.

**Comment by Everhusk** [comment]
Perfect, thanks!
