### ISSUE TITLE
Is there an example implementation of shouldCompact?

### ISSUE THREAD

**Issue by devsales** [realm/realm-js#6044]
In the [React Native SDK docs](https://www.mongodb.com/docs/realm/sdk/react-native/realm-files/) there is a tip:

_Every production application should implement a `shouldCompactOnLaunch` callback to periodically reduce the realm file size._

Is there an example of such an implementation? What would be a "good" condition for this function? I understand that it depends on the use-case but there should be some guidelines about this, right?

The only example I found is in this issue - #5237.

**Comment by kneth** [comment]
From version 11.3.0 our store engine (Realm Core) will remove unused space in order to avoid fast growing Realm files while the app is running (typically when a transaction is committed to disk). Not all unused space can be removed, and using the `shouldCompactOnLaunch` will help you to remove all unused space when the Realm is opened.

The larger a file is, the longer it will take to compact it. The `shouldCompactOnLaunch` function helps you to balance between the need to remove unused space and open the Realm quickly. 

The function in #5237 is saying that if the file is small (less than 100 MB), we don't care about the file. If larger, we only care if half - or more - of the file is unused space. The two thresholds (100 MB and half) are specific to your use case.

**Comment by devsales** [comment]
@kneth thanks for the explanation! So I think the function in #5237 seems reasonable enough. :)
Btw the parameter name seems to be now `shouldCompact` instead of `shouldCompactOnLaunch`..

**Comment by kneth** [comment]
Yes, we renamed it to `shouldCompact` as the old name indicated that it is tied to the app launching and not just opening the file.
