### ISSUE TITLE
Batch update blocking clicking in ListView until finished.

### ISSUE THREAD

**Issue by Jonovono** [realm/realm-js#608]
Hi. So when a user opens my app I make a call to get any new matches they may have. I ideally want to have that just update in the background and immediately return what I have locally stored in Realm. 

I display all the info in a ListView (the one Realm provides). The response may be > 1000 or so and I update ones that are currently in the database, so basically each one gets an update. So I loop through each match and it seems that until that's done I am unable to click on anything. It's all blocked. 

This is what I am doing:

```

function insertMatches(matches) {

  realm.write(() => {
  var m = []
  for (var i = 0; i < matches.length; i++) {
    var match = matches[i];

    insertMatch(match)
  }
  });
}
```

```
function insertMatch(match) {
    realm.create('Match', match, true)
}
```

Any thoughts?

Thanks!

**Comment by alazier** [comment]
Since js is single threaded it isn't really possible to do stuff in the background. At some point we will support async operations that would allow us to do certain types of work on a background thread but that wont arrive for some time. In the meantime if you break up your large inserts into smaller batches and allow the ui/react-native to do what it needs to do inbetween then this might solve the problem.

**Comment by devbriguy** [comment]
I'm having a similar issue. I noticed a spike in CPU usage in Xcode while updating/creating realm records. It locks up the ui until it finishes processing. @alazier What is the recommended batch size?

**Comment by kristiandupont** [comment]
@devibriguy it's hard to recommend a certain batch size as it depends on the number of properties in your class as well as the operating system and device you are running on. I'd try playing around with it a bit until you hit something that works for you.
