### ISSUE TITLE
Unable to open a realm at path '/data/data/[package]/files/stop.realm' Unsupported Realm file format version.

### ISSUE THREAD

**Issue by young-k** [realm/realm-js#612]
I created a Realm database by importing a csv, and am trying to access it on my react-native android app.

I confirmed that the realms were successfully copied over using Realm.copyBundledRealmFiles();

However, I can't seem to access any of them. I tried both 

let realm = new Realm({path: "stop.realm"});

and including a schema inside the constructor, and both didn't work.

I also tried using the realm dates-v5.realm referenced in https://github.com/realm/realm-js/issues/392, and the appropriate schema at https://github.com/realm/realm-js/blob/master/tests/js/realm-tests.js#L798, using the same constructor, and received the same error. 

The project with the error is located at: https://github.com/young-k/rideithaca/tree/cc5e2819f243164cf7ba7bb11b34a98feb4df0e8

**Comment by wafisher** [comment]
It seems that the linked native versions are too old to open the newest version of Realm databases. This isn't a problem if the files are created using `write()` in JS which calls, of course, these old native versions (core?). But it's a problem if you get your Realm database file elsewhere and it's been "upgraded."

From what I can tell, 2.0 broke file compatibility and seeing as this repo hasn't been updated since 9/14 that would probably explain it.

**Comment by kristiandupont** [comment]
That's correct, the browser uses a newer version of the core. @young-k you could try recreating your database with an older browser: https://github.com/realm/realm-browser-osx/releases/tag/1.0.2
