### ISSUE TITLE
Mongo query inefficiencies in Atlas Device Sync syncing

### ISSUE THREAD

**Issue by nickbeaulieu** [realm/realm-js#6120]
### How frequently does the bug occur?

Sometimes

### Description

Hi Realm team,

I am filing this ticket as requested by @ianpward over email. This is an inquiry about realm performance around Mongo queries, and is a reference for your investigation. I do not believe this issue is specific to `realm-js`.

**App Services** https://realm.mongodb.com/groups/632e05374a332334728f1257/apps/638f4bbacfca527011d14f65/dashboard

App ID: `stashpad-bbbqw`

Our Atlas cluster frequently scales up and down due to high CPU usage. There appears to be a high number of disk scans as a part of realm syncing between devices and the app services data.

In general, the scaling happens more frequently than we'd expect for having only a couple of hundred concurrent users at the most. 

As a specific example, here is a spike that caused us to scale from M20 -> M30.
<img width="1219" alt="Screenshot 2023-08-23 at 5 45 41 PM" src="https://github.com/realm/realm-js/assets/36804349/57a97790-f1c9-4b68-9ed4-0cf32f8450a9">

Though there was a relatively small amount of data transferred according to the app services app.
<img width="1033" alt="Screenshot 2023-08-23 at 5 46 10 PM" src="https://github.com/realm/realm-js/assets/36804349/b9b0fe1f-b96b-4572-a081-10b414a33238">

We were not initially concerned by the amount of scaling but were contacted by a MongoDB customer success rep who suggested that scaling this frequently is bad, and that our cluster was having a high number of disk scans and in memory sorts.

Please let me know if I can provide any more information to help further this investigation.

### Can you reproduce the bug?

Sometimes

### Reproduction Steps

Normal use of the Realm JS SDK in both a react native app, and an electron app.

### Version

11.10.1

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

N/A

**Comment by kneth** [comment]
@nickbeaulieu Thank you for reporting. As you mention, the issue is not specific to Realm JS, and I have involve our server team.

**Comment by sean-brandenburg** [comment]
Hi @nickbeaulieu, I poked around at this and it looks like during these periods where your cluster is scaled up, you have a large number of new sessions connecting to the server at once.

I see that earlier today `09/08/23  at around ~10:40 UTC` your cluster scaled up due to high CPU load as you describe. At this time the number of sync sessions open went from `~20` to `~2000` which leads to a lot of concurrent bootstraps (the sessions each catching up to receive the most up to date information). Scaling/High CPU usage under this amount of load is the expected behavior from the server under these conditions. 

It sounds like from your description of your workload that this isn't something that you're expecting. These sessions also look like they drop down then spike back up a few times during this period which is unusual. Hard to say exactly what's causing this without knowing what you're doing on the client side and where your traffic comes from, but as far as I can tell, the server appears to be behaving as expected so might be worth poking into your client code (or auditing the sources of this traffic).

**Comment by nickbeaulieu** [comment]
Hi @sean-brandenburg Thanks very much for your response. This is indeed surprising, as we should be connecting only once at the launch of our app. We only have a few hundred users who could be using the app at most at one given time.

 I do not see a flood of session start events like you describe in the App Services [logs](https://realm.mongodb.com/groups/632e05374a332334728f1257/apps/638f4bbacfca527011d14f65/logs?end_date=2023-09-08T06%3A45%3A00.000-04%3A00&limit=100&start_date=2023-09-08T00%3A00%3A00.000-04%3A00&type=sync) page. Can you provide more information? I see about a dozen session start events on 9/8/23 between ~10:35 UTC and ~10:45 UTC. I am not positive since it is not listed as UTC but that seems to be the case based on the way it is filtering. It is a bit hard to tell since the logs filter goes by local time but displays in UTC (I think). I don't see any spike in the session logs at that time.
<img width="976" alt="Screenshot 2023-09-11 at 4 56 43 PM" src="https://github.com/realm/realm-js/assets/36804349/a6b0c9f2-0835-460a-8066-cb5704287c60">

In any case, 6:40 AM EST would be a strange time for our traffic to spike given the majority of our users are based in the US.

Are you able to suggest the best way to view the sources of this traffic? I'm not really sure where else would be the place to look if the session logs aren't showing it.

Thank you for your time!

**Comment by sean-brandenburg** [comment]
Hi @nickbeaulieu, I did a bit more digging here and it looks like these sessions are actually coming from the piece of the system that sync uses to listen on your synced cluster to propagate updates to client devices (these sessions are filtered in the logs in the UI which explains why you don't see them). 

These spikes in traffic happen when this component restarts (which happens fairly regularly) and all of the sessions need to catch up on the updates that happen in the interim during the restart. If you have a large number of uploads during this window it can lead to these sessions all concurrently doing a lot of work which will cause the large spikes in CPU usage that you're seeing. 

An optimization went into effect in early March of this year that should reduce the number of concurrent session's connecting during this restart period, but can't kick in while sync is running unfortunately. In order to pick up this optimization all you should have to do is [terminate](https://www.mongodb.com/docs/atlas/app-services/sync/configure/pause-or-terminate-sync/#terminate-sync) and re-enable sync.

**Comment by nickbeaulieu** [comment]
Hey @sean-brandenburg, thanks for getting back to me. I understand what you're saying about terminating sync. We will have to make sure we have all of our clients set to `RecoverUnsyncedChanges` before we terminate and re-enable sync. 

We have been considering [moving](https://www.mongodb.com/docs/atlas/app-services/apps/change-deployment-models/) to a global deployment instead of a local one anyways, so perhaps that would be good to do subsequently. Maybe changing the deployment model will take care of it anyways? Is it normal for apps to be terminating and re-enabling sync on a somewhat regular basis?

Feel free to close this ticket.

P.S. You might open an issue internally about the logs filter being in local time and not matching the displayed UTC time (like in the screenshot above). It is a bit confusing to work with when they don't match up in the filter vs. the display.

**Comment by sean-brandenburg** [comment]
Hey @nickbeaulieu

It's worth noting that we (at least for now) recommend against global deployments for sync (see the [deployment models section here](https://www.mongodb.com/docs/atlas/app-services/sync/go-to-production/production-checklist/#app-services-configuration)), but this may change in the future.

In general, sync apps terminate as infrequently as is possible since it can take a bit of time to do the initial population of the metadata that sync needs to function and most production apps want to avoid that downtime. Generally apps will terminate when they want to do one of the things listed here in the [sync termination docs](https://www.mongodb.com/docs/atlas/app-services/sync/configure/pause-or-terminate-sync/#terminate-sync) or in some cases, if sync gets into a bad state for some reason, terminating and re-enabling is often the best way to get back to a working state.

Thank you for feedback on the log filtering. I'll forward this along to the relevant team!

**Comment by nickbeaulieu** [comment]
Thanks for your help @sean-brandenburg!
