### ISSUE TITLE
Declaring a list type with a default value throws an error.

### ISSUE THREAD

**Issue by tarangill** [realm/realm-js#6124]
### How frequently does the bug occur?

Always

### Description

This is one of the properties in my data model:
```
lipsColor: {type: 'double[]', default: [242, 108, 167, 100]},
```

When running the app I get this error:

```
Error: Invalid type declaration for property 'lipsColor' on 'CameraState': Cannot use shorthand '[]' in 'type' or 'objectType' when defining property objects., js engine: hermes
```

The error goes away if there is no default value:
```
lipsColor: 'double[]',
```

### Can you reproduce the bug?

Always

### Version

12.1.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android

### Build environment

Which debugger for React Native: ..

**Comment by tarangill** [comment]
Ok, so this was working in earlier version atleast until `11.10.1`. Somewhere in later versions it got changed. The following works now:

```
lipsColor : {type: "list", objectType: 'double', default: [242, 108, 167, 100]},
```

I'll keep the issue open, because this needs to be updated in the documentation.

**Comment by elle-j** [comment]
Hi @tarangill, good to see you managed to fix it. The property schemas need to be defined using either:
* The object representation (as in your last example)
  * E.g. `lipsColor: { type: "list", objectType: "double" }`
* OR: Shorthand representation
  * E.g. `lipsColor: "double[]"`

For v12, we changed the behavior to no longer allow mixing both object representation and shorthand (as in your original example that threw an error) due to ambiguities that can arise.

Since your schema also needs to define a `default`, you'd need to use the object representation.

For some references, please see:
* [v12 release notes](https://github.com/realm/realm-js/releases/tag/v12.0.0)
* [Documentation](https://www.mongodb.com/docs/realm-sdks/js/latest/types/ObjectSchema.html)

**Comment by elle-j** [comment]
@bloggerklik, for seeing all of the TypeScript types and the available properties on objects, you can browse the [API Reference](https://www.mongodb.com/docs/realm-sdks/js/latest/types/PropertySchema.html). Those should always be up to date with the latest release. For seeing more context and examples, the [MDB Docs](https://www.mongodb.com/docs/realm/sdk/react-native/) is recommended 👍

**Comment by bloggerklik** [comment]
@elle-j Thank you for your answer. It might be better if developers were directed directly to that documentation. Because on the first pages a new developer looks at it says `[]` can be used.

Docs: https://www.mongodb.com/docs/realm/sdk/react-native/model-data/data-types/property-types/

Example: https://www.mongodb.com/docs/realm/sdk/react-native/model-data/relationships-and-embedded-objects/

**Comment by bloggerklik** [comment]
@elle-j Sorry for my absent mindedness. I thought `[]` was completely removed.

**Comment by elle-j** [comment]
No worries 🙂
