### ISSUE TITLE
Logging user after register crashes app in Expo/React Native

### ISSUE THREAD

**Issue by rafalnawojczyk** [realm/realm-js#6146]
### How frequently does the bug occur?

Always

### Description

I'm registering new users in an Expo app.  After register I'm trying to login user, but I'm getting error: 
` WARN  Possible Unhandled Promise Rejection (id: 2):
Error: Broken Promise
Error: Broken Promise
    at Realm_close (native)`

And
` ERROR  [Error: Timed out: Realm could not be downloaded in the allocated time: 30000 ms.]`

When i reload app - it turns out that user is logged in. That is happening all the time. 

### Can you reproduce the bug?

Always

### Reproduction Steps

This is link directly to signup screen that is producing problem. 
First handleSignup fires, and after that useEffect tries to login user:
https://github.com/rafalnawojczyk/CubeRivals/blob/master/src/screens/SignupScreen.tsx

### Version

12.1

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

Android 

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
The error message indicates a timeout when you open the Realm, and not when you log in. Said that, I am curious to see how your email/password auth provider is configured: do you use auto-confirm or do you have a flow to confirm the user?

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please create a new issue if you have new observations to share.

**Comment by steve-gowildly** [comment]
For those that might also be hitting this problem - this is what I did to solve it:

1. Go to App Services -> App Users.
2. Under the Users tab, I deleted all of the users in there for clarity (I'm testing Mongo, this is not a production system). I did this for clarity, not because it's necessary!
3. I re-ran my code (after deleting mongodb-realm directory from my local project - again, not likely necessary, but for clarity!)
4. It didn't work
5. I went back to my Users tab and refreshed the list of users - which showed the newly created Anonymous account.
6. I clicked on the View Activity button to see what that might tell me
7. It told me I hadn't enabled sync on the account :)

So to resolve the issue - I went to Device Sync and went through the "Enable Sync" flow - and the issue was resolved.
