### ISSUE TITLE
Support for UWP (Windows Phone 8+ )?

### ISSUE THREAD

**Issue by machei** [realm/realm-js#626]
Hi guys, 
I would to use Realm for Windows Phone 8 or newer.

Plugin unofficial: https://github.com/ReactWindows/react-native-windows

Realm may to work together with plugin.

**Comment by kristiandupont** [comment]
Hi @machei, we might at some point but there are no specific plans at the moment. You might be interested in https://github.com/realm/realm-dotnet/issues/509

**Comment by Kudo** [comment]
@kristiandupont realm-dotnet seems already support WPF, are there any plans to support react-native-windows WPF version? If not, could you kindly provide some hint to integrate realm-dotnet into realm-js?

**Comment by kristiandupont** [comment]
@Kudo realm-dotnet supports Win32 and thus you can use it for WPF, but WPF is a .Net only framework, it has nothing to do with React Native. Integrating the two is not really possible in any way that I can think of. What are you looking to do?

**Comment by Kudo** [comment]
@kristiandupont I want to simply use realm in React Native Windows.
React Native Windows also support WPF version, that's why I am here to ask.
After digging realm-js code, it seems realm heavily rely on JSC hook that inject `Realm` into JSC context.
Unfortunately, React Native Windows does not use JSC but ChakraCore.
Maybe I should expect RN's CXX bridge comes to Windows and do the injection easier.

**Comment by kristiandupont** [comment]
Oh, you are right, that is indeed a thing. I had no idea!
Yeah, this is the same reason why we are not yet supporting cordova/ionic. V8 and JSCore are already causing quite a few challenges. If you feel like playing with it, be my guest -- we gladly accept external PR's and the JS engines are already abstracted away to some degree, but I am guessing it won't be completely trivial.
