### ISSUE TITLE
Float value changes after writing to realm even for integer part of the complete number

### ISSUE THREAD

**Issue by gauravbordoloi** [realm/realm-js#6293]
### How frequently does the bug occur?
Always

### Description
Float value changes after writing to realm even for integer part of the complete number

    import Realm from "realm"
    
    class TData extends Realm.Object {
        static schema = {
            name: "CategoryModel",
            properties: {
                b: "string",
                a: "double",
                c: "float",
            },
            primaryKey: 'b',
        }
    }
    
    const db = {
        //path: DB_PATH,
        schema: [TData]
    }
    
    let realm = await Realm.open(db);
    
    let p = `${Date.now()}`
    
    let v = 1628899821
    
    realm.write(() => {
        realm.create(TData, { a: v, c: v, b: p })
    })
    
    console.log(realm.objectForPrimaryKey(TData, p).toJSON())![image](https://github.com/realm/realm-js/assets/23193185/2c6a3b80-86dc-45fd-8990-3a05104f5ad3)

### Can you reproduce the bug?
Always

### Version
12.3.1

### What services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
Windows 11

**Comment by kneth** [comment]
@gauravbordoloi 

Thank you for reporting. We (JS + Kotlin) need to investigate why `float` is behaving this time.

**Comment by gauravbordoloi** [comment]
@kneth This hit us on a production environment. Any support on quick will be really helpful else I have to migrate the keys to double. Double is working fine.

**Comment by gauravbordoloi** [comment]
Hi @kneth Any update on this?

**Comment by nirinchev** [comment]
Float values cannot precisely represent integers above ~16 million. This is because a 32-bit float uses 24 bits for the mantissa and 8 bits for the exponent. If you need to represent large integers, you'd need to either use an int, double, or Decimal128. You can find more technical information about this in the answers of [this SO question](https://stackoverflow.com/questions/3793838/which-is-the-first-integer-that-an-ieee-754-float-is-incapable-of-representing-e).
