### ISSUE TITLE
get react-native working reliably on ci

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-js#639]

**Comment by alazier** [comment]
This is not yet done...

**Comment by larkost** [comment]
The proximate issue seems to have been that `xcpretty` was swallowing legitimate error messages. The visible error message (`Early unexpected exit, operation never finished bootstrapping`) was only coming through because it was put to STDERR. I have a PR in that fixes this by printing the full log (STDERR and STDOUT) in the case the `xcodebuild` fails. So in the Jenkins output you will get both the `xcpretty` version as well as the raw output form `xcodebuild` in cases of failure.

A better version would have Jenkins collect the whole build log, allowing for better debugging in normative successes, but that is another project.

@alazier: Since the title of this is a bit broad, would this PR close this issue (assuming that it works to point out actual problems)?

**Comment by alazier** [comment]
@larkost this is a huge improvement. Will fix the outstanding problems and we can open new issues in the future if we continue to have reliability problems.
