### ISSUE TITLE
Custom hook re-render multiple components (All App tree)

### ISSUE THREAD

**Issue by cyril36** [realm/realm-js#6392]
### How frequently does the bug occur?

Always

### Description

Hello,

I would like to have some guidance on my custom hook use case.

I have created a hook that manage my user : 
useUserManager.js looks like :

```
export function useUserManager() {
  const realm = useRealm();
  const realmUser = useUser();

  const user = useObject("User", Realm.BSON.ObjectId(realmUser.id));
  const addUser = useCallback(() => {
    realm.write(() => {
      realm.create(
        User,
        {
          _id: Realm.BSON.ObjectId(realmUser.id),
          name: realmUser?.profile?.name,
          email: realmUser?.profile?.email.toLowerCase(),
        },
      );
    });
  }, [realmUser.id, realmUser?.profile?.email]);
  const addUserCoordinate = useCallback((myCoords) => {.......}
  const removeUserCoordinate = useCallback(() => {.......}
return {user, addUser, addUserCoordinate, removeUserCoordinate}
```

I have a tree of component such as :
> App.js > Parent.js > Child.js

In my Child.js i am creating the user with addUser() and updating the coordinate with addUserCoordinate  (fake example): 

```
{user, addUser, addUserCoordinate} = useUserManager()
if (_.isEmpty(user){
   addUser()
}
addUserCoordinate(myCoords)
```

Now that my user as coordinate in the database i would like to remove those coordinates when the application get closed, So i want to implement the removeCoordinate() function in the return of the useEffect at the highest level of my app (in App.js)

App.js
Hello,

I would like to have some guidance on my hook use case.

I have created a hook that manage my user : 
useUserManager.js looks like :

```
export function useUserManager() {
  const realm = useRealm();
  const realmUser = useUser();

  const user = useObject("User", Realm.BSON.ObjectId(realmUser.id));
  const addUser = useCallback(() => {
    realm.write(() => {
      realm.create(
        User,
        {
          _id: Realm.BSON.ObjectId(realmUser.id),
          name: realmUser?.profile?.name,
          email: realmUser?.profile?.email.toLowerCase(),
        },
      );
    });
  }, [realmUser.id, realmUser?.profile?.email]);
  const addUserCoordinate = useCallback((myCoords) => {.......}
  const removeUserCoordinate = useCallback(() => {.......}
return {user, addUser, addUserCoordinate, removeUserCoordinate}
```

I have a tree of component such as :
> App.js > Parent.js > Child.js

In my Child.js i am creating the user with addUser() and updating the coordinate with addUserCoordinate  (fake example): 

```
{user, addUser, addUserCoordinate} = useUserManager()
if (_.isEmpty(user){
   addUser()
}
addUserCoordinate(myCoords)
```

Now that my user has coordinate in the database i would like to remove those coordinates when the application get closed, So i want to implement the removeCoordinate() function in the return of the useEffect at the highest level of my app (in App.js)

App.js

```
const { removeUserCoordinate } = useUserManager();

  useEffect(() => {
    return () => {
        removeUserCoordinate();
    };
  }, []);
```

But because i am calling the useUserManager hook in App.js, everytime i update the user object in my Child.js component all my app is re-rendering while i would like to have only the Child.js to re-render.

How can I use my useUserManager hook to only re-render Child.js but being able to use it also in App.js to remove information at shutdown?

Should I use something else than a hook?
Should I create Functions instead of hooks?

Thank you for you help

### Can you reproduce the bug?

Always

### Version

"@gorhom/bottom-sheet": "^4.6.0",     "@realm/react": "^0.6.2",     "expo": "^49.0.8",     "expo-dev-client": "~2.4.8",     "expo-splash-screen": "~0.20.5",     "expo-status-bar": "~1.6.0",     "react": "18.2.0",     "react-native": "0.72.6",     "react-native-gesture-handler": "^2.14.1",     "react-native-get-random-values": "~1.9.0",     "react-native-paper": "^5.12.1",     "react-native-reanimated": "^3.6.1",     "react-native-safe-area-context": "^4.8.2",     "realm": "^12.5.1"

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

android

### Build environment

Which debugger for React Native: ..

**Comment by elle-j** [comment]
Hi @cyril36, since you're using `useUser()` in your `useUserManager()`, and you're reusing your hook both at the higher level (`App`) and lower (`Child`), then yes the `App` and its children will rerender whenever you make changes to the user in `Child`. This is specific to rerendering in React and not Realm related.

There are various things you could do:
1. In your higher level component (`App`) you could try using a regular function instead of your hook like you mentioned.
2. You could pull `const user = useObject(..)` out of your hook and into another custom hook.
3. You can memoize (`React.memo`) components to keep them from rerendering unnecessarily. Although, memoization also comes with its cost and shouldn't really be needed that often.

Keep in mind that:
* Unless it's very important for your app to minimize rerenders, extra rerenders are not always that big of an issue.
* If you want to reuse object instances and functions created in managers (such as in your hook) in multiple places in your app, look into `React.createContext`. This way, those will be shared, whereas if using your custom hook, it is duplicated.

Hope this helps you @cyril36, but again, since this particular issue is mainly about guidance around React Native usage, please use our [Community Forum](https://www.mongodb.com/community/forums/t/custom-hook-re-render-multiple-components-all-app-tree/262527).
