### ISSUE TITLE
Change encryption key (based on username and password)

### ISSUE THREAD

**Issue by stewart42** [realm/realm-js#650]
Hi 

I am busy implementing realm in a `react-native` project and I want to use the `encryptionKey` config option. 

I would like to use the users credentials to create the key, what I am not sure about is how to deal with the credentials changing and therefore the `encryptionKey` changing. I can't see anything in the docs about how to either remove / delete the realm db or change the `encryptionKey` which it was encrypted with?

I am not adverse to using a static private key but this does introduce challenges with storing it securely? 

Any help or pointers to docs / examples would be greatly be appreciated.

**Comment by kristiandupont** [comment]
Hi @stewart42, yeah, the solution is to copy the realm and then delete the old one. But as you've noted, there is no `deleteRealm` function in the JS SDK yet. Keep an eye on #363.

The risk with using a static private key is that someone will extract it from your binary. You may or may not be ok with that. There are some discussions on how to alleviate the problem here http://stackoverflow.com/questions/14570989/best-practice-for-storing-private-api-keys-in-android and http://stackoverflow.com/questions/29760216/in-ios-how-can-i-store-a-secret-key-that-will-allow-me-to-communicate-with-my

**Comment by stewart42** [comment]
thanks @kristiandupont will follow #363
