### ISSUE TITLE
Zipped realm dependency is over 100MB

### ISSUE THREAD

**Issue by georgeevans1995** [realm/realm-js#6740]
### How frequently does the bug occur?

Always

### Description

I just updated to realm 12.11.0 and can't push changes to github as the zipped dependency for realm is  175MB. Looks like the zip file is over 3 times larger then 12.10.0, have some files been added to the bundle by accident maybe?

### Stacktrace & log output

```shell
File .yarn/cache/realm-npm-12.11.0-6c3752aa4e-bf4ab585b4.zip is 179.50 MB; this exceeds GitHub's file size limit of 100.00 MB
```

### Can you reproduce the bug?

Always

### Reproduction Steps

using yarn. yarnrc.yml looks like the below:

```
enableImmutableInstalls: false
nmHoistingLimits: workspaces
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.5.1.cjs
```

### Version

12.11.0

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

Mac Sonoma 14.3

### Build environment

Which debugger for React Native: ..

**Comment by nirinchev** [comment]
This is due to now including prebuilds for android in the package, which was introduced in https://github.com/realm/realm-js/pull/6650. In general, committing dependencies to git is bad practice as those can be downloaded post cloning from npm. If you absolutely need to store the dependencies in git, then it's best to do that using [git lfs](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage), regardless of their size.
