### ISSUE TITLE
Expo EAS build started failing with  command not found: cmake-js

### ISSUE THREAD

**Issue by jsmircic** [realm/realm-js#6813]
### How frequently does the bug occur?

always 

### Description

Suddenly  our `react-native` android app builds are failing on EAS build service. looks like problem is with realm build. we see an error `command not found: cmake-js`. The same issue #4618  was happening about 2 years ago and there was some expired certificate problem. Is it possible same thing is happening again?

### Stacktrace & log output

```shell
YN0000: │ realm@npm:11.10.2 [bfe5d] STDERR prebuild-install warn install getaddrinfo ENOTFOUND static.realm.io
➤ YN0000: │ realm@npm:11.10.2 [bfe5d] STDERR command not found: cmake-js
➤ YN0009: │ realm@npm:11.10.2 [bfe5d] couldn't be built successfully (exit code 127, logs can be found here: /tmp/xfs-6a37f5f9/build.log)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

eas build --platform android

### Version

11.10.2

### What services are you using?

Local Database only

### Are you using encryption?

-- select --

### Platform OS and version(s)

react-native 0.74.1

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment]
Thanks for reporting this!

We had a brief outage of our `static.realm.io` domain, which prevented the Node.js prebuild binary from being downloaded. This results in a fallback behaviour of trying to build from source (which it can't because of the missing dev-dependencies - `cmake-js` included). We've since removed this fallback behaviour from the v12 of our SDK.

The domain is now up again 🎉
We're really we're sorry for any inconvenience might have caused you or any of our other users.

**Comment by jsmircic** [comment]
Yep, all good now, thank you.
