### ISSUE TITLE
Filtering from a nested List Object

### ISSUE THREAD

**Issue by amanthegreatone** [realm/realm-js#881]
Hi,

I am getting an issue trying to filter data from a nested list. My schema:

```
export const UserTenants = {
  name: 'UserTenants',
  primaryKey: 'id',
  properties: {
    id: 'string',//stored as string due to microservice stringifying the tenants
    tenant: 'string',
    user_id: 'string',//stored as string due to microservice stringifying the tenants
  }
};

//basic user profile to map tenants
//query each tenant from this list for its master details
export const UserProfile = {
  name: 'UserProfile',
  primaryKey: 'mobile',
  properties: {
    id: 'int',
    mobile: 'string',
    tenants: {type: 'list', objectType: 'UserTenants'},
  }
};

//persist the login details to login automatically when the app starts
export const UserLogin = {
  name: 'UserLogin',
  properties: {
    id: 'int',
    tenant: 'string',
    authToken: 'string',
  }
};
```
Trying to find the user_id of a tenant from the list of tenants using this query. It is not filtering as expected and I am always getting the whole UserProfile object.

```
export function getUserIdForTenant(tenant){
  userProfile = realm.objects(UserProfile.name).filtered(`tenants.tenant == "${tenant}"`);
  console.log("userprofile results", userProfile);
  userId = userTenants.user_id;
  return parseInt(userId);
}
```

sample userProfile object : 

```
{
  id: 6,
  mobile: '1111111111',
  tenants:[
    {
      id: "1",
      tenant: 'tenant 1',
      user_id: "1",
    },
    {
      id: "2",
      tenant: 'tenant 2',
      user_id: "2",
    },
  ],
}
```

I want to find the user_id in tenant 2. Can someone help me with this query.

realm 0.15.4
RN 0.40.0
testing on ios sim

**Comment by fealebenpae** [comment]
Hey @amanthegreatone,

realm-js doesn't support template literal strings in queries. You need to use the following format: `.filtered('tenants.tenant = $0', tenant)`.
Please let me know if this helps.

**Comment by amanthegreatone** [comment]
Nope, this also doesn't work. 

BTW the template literal strings does work for me perfectly in all other cases. I have a lot of queries like below that are working fine. Only having issues with the list.

`results = realm.objects(InternalTask.name).filtered(`tenant == "${tenant}" AND task_status == "${status}"`);`

**Comment by fealebenpae** [comment]
Ah, sorry I didn't see this earlier, but you're trying to filter on the contents of a to-many relationship, which is definitely not supported.

Realm has a feature called inverse relationships which allows realm objects to access other objects that link to them in a specific relationship and these kinds of queries are usually implemented on top of this feature. [It's not implemented yet in realm-js](https://github.com/realm/realm-js/issues/343), unfortunately, but this is how I believe it'd accomplish what you're trying to do:
```js
const UserTenants = {
  name: 'UserTenants',
  primaryKey: 'id',
  properties: {
    id: 'string',//stored as string due to microservice stringifying the tenants
    tenant: 'string',
    user_id: 'string',//stored as string due to microservice stringifying the tenants
    user_profiles: { type: 'backlink', objectType: 'UserProfile', property: 'tenants' }
  }
};

const UserProfile = {
  name: 'UserProfile',
  primaryKey: 'mobile',
  properties: {
    id: 'int',
    mobile: 'string',
    tenants: {type: 'list', objectType: 'UserTenants'},
  }
};

let realm = new Realm({ schema: [ UserTenants, UserProfile ] });
const tenant = '...';
let profiles = realm.objects('UserTenants').filtered('tenant == $0', tenant)[0].user_profiles;
```

My mistake was misreading your code and assuming you were trying to filter on a realm object value and not a string value. Of course interpolated strings work fine when the query parameters are strings or numbers, but you would need the original syntax when the parameter type is RealmObject, ArrayBuffer, or Date, because stringifying those would strip them of the information realm-js needs to build the query.

I'm afraid that until realm-js supports nested list filtering or inverse relationships, you'd need to use the workaround you've implemented.

**Comment by amanthegreatone** [comment]
thanks for clarifying everything :)
