### ISSUE TITLE
Clear all versions

### ISSUE THREAD

**Issue by thiagoterleski** [realm/realm-js#982]
Hi! How can I clear all my database and versions?

**Comment by istx25** [comment]
HI @thiagoterleski.

Just as a side note (for next time): questions like these are best for Stack Overflow. Just make sure to include the 'realm' tag and we'll respond as quickly as we do here since it's monitored. We would like to reserve GitHub for primarily bug reports and feature requests. ❤️ 🙌 

But nevertheless, thank you for reaching out. **JavaScript isn't my strongest language so the syntax may be off. However, realm-js has a function named [`deleteAll`](https://realm.io/docs/javascript/1.0.0/api/Realm.html#deleteAll) which deletes all objects in the realm that it is called on.

And you'd use it this way:

```javascript
let realm = new Realm(); // This may be the incorrect way to initialize a Realm in JS. 
realm.deleteAll();
```
_(Realm staff: Feel free to edit my code block if anything is incorrect.)_

Please let us know if you have any further questions.

**Comment by blagoev** [comment]
closing this since I believe the question was answered
